<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-orange">
            <div class="panel-heading">
                <?php echo $this->translate("Export Data");?>
            </div>
            <div class="panel-body" align="center">
                <p>

                    <form id="defaultForm" method="post" class="form-horizontal" style="margin-top: 20px;" action="<?php echo $this->url(array("controller" => "ranking-report", "action" => "csv"), null, false); ?>" METHOD="post"> 
                        <div class="zend_form" id="form_ie">
                            <h4>
                                <span><?php echo $this->translate("Export to CSV")?></span>
                                <br><br>
                            </h4>

                            <?php echo $this->translate("Total entries to be exported: ")?>
                            <b><?php echo $this->quant; ?></b>
                            
                            <input type="hidden" name="ranking" value="<?php echo $this->ranking; ?>">
                        
                            <div class="snep-body-footer-buttons">
                                <input type="submit" class="btn btn-add btn-primary" style="width:100px;" name="submit" id="submit" title="Download" value="Download">&nbsp;&nbsp;&nbsp;
                                <a class="btn btn-outline btn-add" href="javascript:window.history.go(-1)" role="button"><?php echo $this->translate("Cancel")?></a>
                            </div> 
                        </div> 
                    </form>
                </p>
            </div>
        </div>
    </div>   
</div>