<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/css/diagnostic.css"); ?>
<div class="snep_form">
    <p>
        <?php echo $this->translate("You must correct any errors highlighted in red for this step of the installation. It is important that all errors are corrected for the SNEP work properly. Advanced users can skip this part of the installation if you wish, this diagnosis can be accessed from within the system menu choice <strong>Settings</strong> > <strong>Diagnostics </strong>."); ?>
    </p>

    <div class="inspect">
        <ol>    
            <ul>
               <?php foreach( $this->testResult as $chave => $valor ): ?>

                   <?php $style = ( $valor['error'] ? 'list_error' : 'list_no_error' ); ?>
                    <li class='<?php echo $style?>'><h2> <?php echo $valor['name'] ?> </h2> </li>
                    <?php if ($valor['error']): ?>
                        <li style="background-color:#FFEDED"> <pre> <?php echo $valor['message'] ?> </pre> </li>
                    <?php endif ?>

                <?php endforeach ?>
            </ul>
        </ol>
    </div>    
</div>


<div class="zend_form_submit" style="width: 460px;margin: 0 auto; padding: 10px 0px;">
    <?php if($this->errored): ?>
        <button onclick="location.reload(true)"><?php echo $this->translate("Test again"); ?></button>        
        <input type="submit" onclick="location.href='<?php echo $this->next;?>'" value="<?php echo $this->translate("Continue"); ?>"  />
        <a class="snep_form_cancel" href="javascript:location.href='javascript:history.back();'">Cancel</a>
    <?php else: ?>
        <input type="submit" onclick="location.href='<?php echo $this->next;?>'" value="<?php echo $this->translate("Next"); ?>">
        <a class="snep_form_cancel" href="javascript:location.href='javascript:history.back();'">Cancel</a>
    <?php endif;?>
</div>