<div class="snep_form">
<?php
    if( $this->error['error'] ) : ?>
        <div class="error_box"> <?php echo $this->error['message']  ?> </div>
    <?php endif ?>

    <div class="info_box">
        <h1> <?php echo $this->translate("Welcome to SNEP!"); ?> </h1>

        <p>
        <?php echo $this->translate("You will be taken in the installation of SNEP"); ?>
        </p>
        <ul>
            <li><?php echo $this->translate("Language selection and location") ?></li>
            <li><?php echo $this->translate("Diagnosis System") ?></li>
            <li><?php echo $this->translate("Configuration of access to the database, Asterisk"); ?></li>
            <li><?php echo $this->translate("Set Password Administrator"); ?></li>
        </ul>
    </div>
</div>

<?php echo $this->form ?>

