<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/css/agi_rules.css"); ?>

<h1><?php echo $this->translate("The SNEP was successfully installed."); ?></h1>

<p>
    <?php echo $this->translate("The SNEP was successfully installed on your system, click the button below to go to the login screen."); ?>
</p>

<p>
    <?php echo $this->translate("The password for the Admin user has been reset in the installation, store it safely."); ?>
</p>

<div class="info_box">
    <ul>
        <li> <b> <?php echo $this->translate("Usuário"); ?> :</b> <?php echo $this->secret['name'] ?> </li>
        <li> <b> <?php echo $this->translate("Senha"); ?> :</b> <?php echo $this->secret['password'] ?> </li>
    </ul>
</div>


<p class="installer_buttons">
    <button onclick="location.href='<?php echo $this->baseUrl();?>'"><?php echo $this->translate("Ir para o SNEP"); ?></button>
</p>