<?php
$this->headLink()->appendStylesheet($this->baseUrl() . "/includes/javascript/datatables/media/css/dataTables.bootstrap.css");
$this->headLink()->appendStylesheet($this->baseUrl() . "/includes/javascript/datatables/resources/syntax/shCore.css");
$this->headLink()->appendStylesheet($this->baseUrl() . "/includes/javascript/datatables/media/css/buttons.dataTables.css");
$this->headLink()->appendStylesheet($this->baseUrl() . "/includes/javascript/datatables/resources/demo.css");
?>

<script src="/snep/includes/javascript/datatables/media/js/jquery.dataTables.js" type="text/javascript"></script>
<script src="/snep/includes/javascript/datatables/media/js/dataTables.bootstrap.js" type="text/javascript"></script>
<script src="/snep/includes/javascript/datatables/resources/syntax/shCore.js" type="text/javascript"></script>
<script src="/snep/includes/javascript/datatables/resources/demo.js" type="text/javascript"></script>
<script src="/snep/includes/javascript/datatables/datatables.net-buttons/js/dataTables.buttons.min.js" type="text/javascript"></script>
<script src="/snep/includes/javascript/datatables/media/js/jszip.min.js" type="text/javascript"></script>
<script src="/snep/includes/javascript/datatables/pdfmake/pdfmake.min.js" type="text/javascript"></script>
<script src="/snep/includes/javascript/datatables/pdfmake/vfs_fonts.js" type="text/javascript"></script>
<script src="/snep/includes/javascript/datatables/datatables.net-buttons/js/buttons.html5.min.js" type="text/javascript"></script>



<div class="row">

  <div class="tab-content">
    <div class="tab-pane active" id="demo">
      <table class="table table-striped" id="analytic">
        <thead>
          <tr>
            <th class="text-center"><?php echo $this->translate("Activity date") ?></th>
            <th class="text-center"><?php echo $this->translate("IP") ?></th>
            <th class="text-center"><?php echo $this->translate("User") ?></th>
            <th class="text-center"><?php echo $this->translate("Action") ?></th>
            <th class="text-center"><?php echo $this->translate("Table") ?></th>
            <th class="text-center"><?php echo $this->translate("Description") ?></th>
          </tr>
        </thead>
        <tbody class="table-data">
          <?php
foreach ($this->logs as $log) {?>
            <tr>
              <td class="text-center"><?php echo date('d/m/Y H:i:s', strtotime($log['datetime'])) ?></td>
              <td class="text-center"><?php echo $log['ip']; ?></td>
              <td class="text-center"><?php echo $log['user']; ?></td>
              <td class="text-center"><h4><span class="<?php echo $log['class']; ?>"><?php echo $this->translate($log['action']); ?></span></h4></td>
              <td class="text-center"><?php echo $log['table']; ?></td>
              <td class="text-center"><?php echo $log['description']; ?></td>
            </tr>
            <?php }?>
          </tbody>
        </table>
        <div class="snep-body-footer-buttons">
          <a class="btn btn-outline btn-add" href="javascript:window.history.go(-1)" role="button"><?php echo $this->translate("Back") ?></a>
        </div>
      </div>
    </div>
  </div>

<script type="text/javascript">

jQuery.noConflict();

jQuery(document).ready(function() {
  jQuery('#analytic').dataTable( {
    "pageLength": <?php echo $this->lineNumber ?>,
    "oLanguage": {
      "sUrl": "/snep/includes/javascript/datatables/media/language/pt-BR.json"
    },
    dom: 'Bfrtip',
    buttons: [
      {
        extend: 'excelHtml5',
        title : "SNEP - Auditoria"
      },
      {
        extend: 'csvHtml5',
        title : "SNEP - Auditoria"
      },
      {
        extend: 'pdfHtml5',
        title : "SNEP - Auditoria"
      }
    ]
  });
});

</script>
