<?php
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/index.css");
$this->headScript()->appendFile($this->baseUrl() . '/includes/javascript/scriptaculous/lib/prototype.js');
$this->headScript()->appendFile($this->baseUrl() . "/includes/javascript/scriptaculous/src/scriptaculous.js", 'text/javascript');
$this->headScript()->appendFile('/snep/includes/javascript/enableField.js');
?>

<form method="post">
    <table>

        <thead>
            <tr>
                <th> <?php echo $this->translate('Code') ?> </th>
                <th class="action"> <?php echo $this->translate('Active') ?> </th>
                <th class="action"> <?php echo $this->translate('Recording') ?> </th>
                <th> <?php echo $this->translate('Restricted Access') ?> </th>
                <th> <?php echo $this->translate('Cost Center') ?> </th>

            </tr>
        </thead>
        <tbody>
            <?php
            $c = 0;

            if ($this->conferenceRooms):

                foreach ($this->conferenceRooms as $id => $conferenceRooms):
                    ?>

                    <?php ($c ? $c = 0 : $c = 1 ); ?>
                    <tr class="c<?php echo $c ?>">
                        <td class="numeric"> <b> <?php echo $conferenceRooms['id'] ?> </b> </td>
                        <td class="action">
                            <?php ( $conferenceRooms['status'] ? $chek = 'checked' : $chek = '') ?>
                            <input type="checkbox" id="hab_<?php echo $conferenceRooms['id'] ?>" class="newcheck" onclick="habilita('<?php echo $conferenceRooms['id'] ?>');" <?php echo $chek ?> value="<?php $conferenceRooms['status'] ?>"  name="activate[<?php echo $conferenceRooms['id'] ?>]">
                        </td>
                        <td class="action">
                            <?php ( $conferenceRooms['rec'] ? $chek = 'checked' : $chek = '') ?>

                            <input type="checkbox" class="newcheck" <?php echo $chek ?> value="<?php $conferenceRooms['rec'] ?>"  name="rec[<?php echo $conferenceRooms['id'] ?>]">
                        </td>
                        <td class="password">

                            <?php
                            if (empty($conferenceRooms['authenticate'])) {

                                $checked = '';
                                $display = "style=\"display:none;\"";
                            } else {

                                $checked = 'checked';
                                $display = '';
                            }
                            ?>                    
                            <input id="auth_<?php echo $conferenceRooms['id'] ?>" type='checkbox' disabled="true" <?php echo $checked ?> name='authenticate[<?php echo $conferenceRooms['id'] ?>]' onclick="pass('<?php echo $conferenceRooms['id'] ?>');">
                            <?php echo $this->translate('Password Authentication') ?>
                            <div id="box_<?php echo $conferenceRooms['id'] ?>"  <?php echo $display ?> >                        
                                <input type="password" name="password[<?php echo $conferenceRooms['id'] ?>]" onkeydown = "BloqueiaComando(event)" onkeypress="return onlyDigit(event)"  value="<?php echo $conferenceRooms['authenticate'] ?>">
                                <small> <?php echo $this->translate('( Only numbers)') ?></small>
                            </div>
                        </td>

                        <td>
                            <select name="costCenter[<?php echo $conferenceRooms['id'] ?>]">
                                <?php foreach ($this->costCenter as $chave => $costCenter): ?>

                                    <?php ( $conferenceRooms['ccustos'] == $costCenter['codigo'] ? $select = 'selected' : $select = '' ); ?>

                                    <option value="<?php echo $costCenter['codigo'] ?>" <?php echo $select ?> >
                                        <?php echo $costCenter['tipo'] . " : " . $costCenter['codigo'] . " - " . $costCenter['nome']; ?>
                                    <?php endforeach ?>
                            </select>
                        </td>

                    </tr>
                <?php endforeach ?>
            <?php endif ?>
            <tr>
                <td height="40" valign="middle" colspan="5">
        <center>
            <input type="submit" class="button" name="conference" value='<?php echo $this->translate('Save') ?>'/>
        </center>
        </td>
        </tr>
        </tbody>
    </table>
</form>

<script type="text/javascript">
    function pass(id) {
        if (document.getElementById('box_' + id).style.display == '') {
            document.getElementById('box_' + id).style.display = 'none';
        } else {
            document.getElementById('box_' + id).style.display = '';
        }
    }

    function onlyDigit(e) {
        var unicode = e.charCode ? e.charCode : e.keyCode;
        if (unicode != 8 && unicode != 9) {
            if (unicode < 48 || unicode > 57) {
                return false
            }
        }
    }

    function BloqueiaComando(event) {
        var tecla = String.fromCharCode(event.keyCode).toLowerCase();

        if (event.ctrlKey && (tecla == "c" || tecla == "v")) {
            window.event ? event.returnValue = false : event.preventDefault();
            return false
        }
    }

    function click() {
        if (event.button == 2 || event.button == 3) {
            oncontextmenu = 'return false';
        }
    }
    document.onmousedown = click
    document.oncontextmenu = new Function("return false;")

    function habilita(id) {

        if (document.getElementById('hab_' + id).checked == true) {
            document.getElementById('auth_' + id).disabled = false;
        } else {
            document.getElementById('auth_' + id).disabled = true;
        }
    }

</script> 