<?php
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/index.css");
$this->headScript()->appendFile($this->baseUrl() . '/includes/javascript/scriptaculous/lib/prototype.js');
$this->headScript()->appendFile($this->baseUrl() . "/includes/javascript/scriptaculous/src/scriptaculous.js", 'text/javascript');
$this->headScript()->appendFile($this->baseUrl() . '/includes/lightbox.js', 'text/javascript');
?>
<form method="post">
    <table>
        <div id="lightboxbody">
            <a id="lightboxLink" href="javascript:void(0);"><img src="/snep/imagens/help.png" class="right"></a>
        </div>

        <div id="containerDiv">
            <h2><?php echo $this->translate("Salas de conferência"); ?></h2>

            <?php echo $this->translate("A conferência consiste em adicionar uma ou mais pessoas a uma conversa, 
            possibilitando que sejam feitas salas de conferência.Os números das Salas de 
            Conferências são pré­determinados na Instalação do SNEP, e são reconhecidos 
            no Sistema como se fossem um “RAMAL”."); ?>

            <br><strong><?php echo $this->translate("Código:"); ?></strong> 
            <?php echo $this->translate("Código da sala de conferência."); ?>

            <br><strong><?php echo $this->translate("Senha:"); ?></strong>
            <?php echo $this->translate("Senha da sala de conferência."); ?>

            <br><strong><?php echo $this->translate("Centro de custo:"); ?></strong> 
            <?php echo $this->translate("Centro de custo da sala de conferência."); ?>

            <br><strong><?php echo $this->translate("Ativo:"); ?></strong>
            <?php echo $this->translate("Ativa ou desativa a sala de conferência."); ?>

            <br><strong><?php echo $this->translate("Gravação:"); ?></strong>
            <?php echo $this->translate("Ativa ou desativa a gravação da sala de conferência."); ?>
            <br>
            <br>
            <a id="closeLink" href="javascript:void(0);"><?php echo $this->translate("Back"); ?></a><br><br>
        </div> 
        <thead>
            <tr>
                <th> <?php echo $this->translate('Code') ?> </th>
                <th> <?php echo $this->translate('Restricted Access') ?> </th>
                <th> <?php echo $this->translate('Cost Center') ?> </th>
                <th class="action"> <?php echo $this->translate('Active') ?> </th>
                <th class="action"> <?php echo $this->translate('Recording') ?> </th>
            </tr>
        </thead>
        <tbody>
            <?php
            $c = 0;

            if ($this->conferenceRooms):

                foreach ($this->conferenceRooms as $id => $conferenceRooms):
                    ?>

                    <?php ($c ? $c = 0 : $c = 1 ); ?>
                    <tr class="c<?php echo $c ?>">
                        <td class="numeric"> <b> <?php echo $conferenceRooms['id'] ?> </b> </td>
                        <td class="password">

                            <?php
                            if (empty($conferenceRooms['authenticate'])) {

                                $checked = '';
                                $display = "style=\"display:none;\"";
                            } else {

                                $checked = 'checked';
                                $display = '';
                            }
                            ?>                    
                            <input type='checkbox' <?php echo $checked ?> name='authenticate[<?php echo $conferenceRooms['id'] ?>]' onclick="pass('<?php echo $conferenceRooms['id'] ?>');">
                            <?php echo $this->translate('Password Authentication') ?>
                            <div id="box_<?php echo $conferenceRooms['id'] ?>"  <?php echo $display ?> >                        
                                <input type="password" name="password[<?php echo $conferenceRooms['id'] ?>]"  value="<?php echo $conferenceRooms['authenticate'] ?>">
                                <small> <?php echo $this->translate('( Only numbers)') ?></small>
                            </div>
                        </td>

                        <td>
                            <select name="costCenter[<?php echo $conferenceRooms['id'] ?>]">
                                <?php foreach ($this->costCenter as $chave => $costCenter): ?>

                                    <?php ( $conferenceRooms['ccustos'] == $costCenter['codigo'] ? $select = 'selected' : $select = '' ); ?>

                                    <option value="<?php echo $costCenter['codigo'] ?>" <?php echo $select ?> >
                                        <?php echo $costCenter['tipo'] . " : " . $costCenter['codigo'] . " - " . $costCenter['nome']; ?>
                                    <?php endforeach ?>
                            </select>
                        </td>
                        <td class="action">
                            <?php ( $conferenceRooms['status'] ? $chek = 'checked' : $chek = '') ?>
                            <input type="checkbox" class="newcheck" <?php echo $chek ?> value="<?php $conferenceRooms['status'] ?>"  name="activate[<?php echo $conferenceRooms['id'] ?>]">
                        </td>
                        <td class="action">
                            <?php ( $conferenceRooms['rec'] ? $chek = 'checked' : $chek = '') ?>

                            <input type="checkbox" class="newcheck" <?php echo $chek ?> value="<?php $conferenceRooms['rec'] ?>"  name="rec[<?php echo $conferenceRooms['id'] ?>]">
                        </td>
                    </tr>
                <?php endforeach ?>
            <?php endif ?>
            <tr>
                <td height="40" valign="middle" colspan="5">
        <center>
            <input type="submit" class="button" name="conference" value='<?php echo $this->translate('Save') ?>'/>
        </center>
        </td>
        </tr>
        </tbody>
    </table>
</form>

<script type="text/javascript">
                        function pass(id) {
                            if (document.getElementById('box_' + id).style.display == '') {
                                document.getElementById('box_' + id).style.display = 'none';
                            } else {
                                document.getElementById('box_' + id).style.display = '';
                            }
                        }
                        var test;

                        Event.observe(window, 'load', function() {
                            test = new Lightbox('containerDiv');
                        });
                        Event.observe('lightboxLink', 'click', function() {
                            test.open();
                        });
                        Event.observe('closeLink', 'click', function() {
                            test.close();
                        });
</script>