<?php
//
$this->headScript()->appendFile($this->baseUrl() . "/includes/javascript/scriptaculous/src/scriptaculous.js", 'text/javascript');
$this->headScript()->appendFile($this->baseUrl() . '/includes/lightbox.js', 'text/javascript');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/main.css');
?>

<?php echo $this->doctype(); ?>
<html>
    <head>
        <?php echo $this->headTitle() . "\n"; ?>
        <?php echo $this->headLink() . "\n"; ?>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headStyle() . "\n"; ?>
        <?php echo $this->headScript() . "\n"; ?>
        <?php
        $controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
        $module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();

        ?>
    </head>
    <body>
        <!-- ugly markup for footer pindown -->
        <div id="wrapper">
            <div id="header">
                <a href="<?php echo Zend_Registry::get('config')->system->path->web; ?>/index.php/" alt="inicio" title="inicio">
                    <img src="<?php echo $this->baseUrl(); ?>/imagens/snep_logo.png" alt="SNEP" id="snep_logo" />
                </a>
            </div>
            <?php if (!$this->hideMenu): ?>

                <div id="menus">

                    <ul class="navmenu rightmenu">
                        <li>
                            <a href="<?php echo $this->baseUrl(); ?>/index.php/default/auth/logout"><?php echo $this->translate("Logout"); ?></a>
                        </li>
                    </ul>

                    <!-- Help --> 
                    <div>
                        <a id="lightboxLink" href="javascript:void(0);"><img src="/snep/imagens/help.png" class="right"></a>
                    </div>

                    <div id="containerDiv">
                        <?php
                        $locale = Zend_Registry::get('config')->system->language;

                        $homepage = file_get_contents('/var/www/snep/modules/' . $module . '/help/' . $locale . '/' . $controller . '.html');

                        if ($homepage) {
                            echo $homepage;
                        } else {
                            $homepage = file_get_contents('/var/www/snep/modules/default/help/' . $locale . '/error.html');
                            echo  $homepage;
                        }
                        ?>

                        <br>
                        <a id="closeLink" href="javascript:void(0);"><?php echo $this->translate("Back"); ?></a><br><br>
                    </div>
                    
                    <ul class="navmenu">
                        <?php echo Snep_Menu::getMasterInstance()->renderChildren(); ?>
                        <li id="default_modules" onclick="modules('maisinfo');"><a href="#"><?php echo $this->translate("Modules"); ?></a>
                        </li>
                    </ul>

                    <div id="maisinfo" style="display:none">
                        <ul class="navmenuModule">
                            <?php echo Snep_Menu::getMasterInstance()->renderChildrenModule(); ?>
                        </ul>  
                    </div>
                    

                </div>
            <?php endif; ?>
            <div id="breadcrumb" <?php
            if ($this->hideMenu) {
                echo 'class="fullbreadcrumb"';
            }
            ?>>
                     <?php echo $this->breadcrumb; ?>
            </div>
            <div id="content">
                <?php echo $this->layout()->content; ?>
            </div>
            <div class="push"></div>
        </div>
        <div id="footer">
            <div id="footer_content">
                <p id="footer_vendor"><?php echo SNEP_VENDOR; ?></p>

                <!-- Language -->
                <?php
                if ($controller != "auth") {
                    $eng = '<img src="/snep/imagens/Eua.png" class="right" title="Click to change language to english";">';
                    $port = '<img src="/snep/imagens/Brazil.png" class="right" title="Clique para mudar o idioma para português";">';
                    $es = '<img src="/snep/imagens/es.png" class="right" title="Clique para mudar o idioma para espanhol";">';

                    echo "<a href=\"{$this->PAGEINFO}/snep/index.php/default/parameters/eng?module=$controller\">$eng<a/>";
                    echo "<a href=\"{$this->PAGEINFO}/snep/index.php/default/parameters/es?module=$controller\">$es<a/>";
                    echo "<a href=\"{$this->PAGEINFO}/snep/index.php/default/parameters/port?module=$controller\">$port<a/>";

                }
                ?>


                <p id="footer_version">Snep <?php echo SNEP_VERSION ?></p>
            </div>
        </div>
    </body>
</html>

<script language="javascript" type="text/javascript">
    var test;

    Event.observe(window, 'load', function() {
        test = new Lightbox('containerDiv');
    });
    Event.observe('lightboxLink', 'click', function() {
        test.open();
    });
    Event.observe('closeLink', 'click', function() {
        test.close();
    });

    var modules = function(obj) {

        var el = document.getElementById(obj);
        if (el.style.display != 'none') {
            el.style.display = 'none';
        }
        else {
            el.style.display = '';
        }
    }
</script>