<!DOCTYPE HTML>
<html>
<head>
<title>SNEP - Login</title>
<!-- Custom Theme files -->
<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/css/login.css?id=" . time()); ?>
<!-- Custom Theme files -->
<?php echo $this->headScript()->appendFile($this->baseUrl() . '/includes/javascript/notifications.js'); ?>
<?php echo $this->headScript()->appendFile($this->baseUrl() . '/includes/javascript/jquery.min.js'); ?>
<?php echo $this->headLink() . "\n"; ?>
<?php echo $this->headMeta(); ?>
<?php echo $this->headStyle() . "\n"; ?>
<?php echo $this->headScript() . "\n"; ?>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!--script-->
<?php echo $this->headScript()->appendFile($this->baseUrl() . '/includes/javascript/easyResponsiveTabs.js'); ?>

<script type="text/javascript">
var session = "<?php echo $this->language; ?>";
  $(document).ready(function () {
      $('#horizontalTab').easyResponsiveTabs({
          type: 'default', //Types: default, vertical, accordion
          width: 'auto', //auto or any width like 600px
          fit: true   // 100% fit in a container
      });
  });

</script>
</head>
<body onload="getAnnounce(session);">
	<div class="head">
		<div class="login">
			<div align="center"><img src="<?php echo $this->baseUrl(); ?>/images/logo-snep.png" width="50%"><br>
      <a href="<?php echo $this->baseUrl(); ?>/index.php/default/auth?indexChooseLanguage=en">
				<img src="<?php echo $this->baseUrl(); ?>/images/Eua.png" width="16px">
      </a>
      <a href="<?php echo $this->baseUrl(); ?>/index.php/default/auth?indexChooseLanguage=pt_BR">
				<img src="<?php echo $this->baseUrl(); ?>/images/Brazil.png" width="16px">
      </a>
      <a href="<?php echo $this->baseUrl(); ?>/index.php/default/auth?indexChooseLanguage=es">
				<img src="<?php echo $this->baseUrl(); ?>/images/es.png" width="16px"><br>
      </a>
				</div>
			<div class="sap_tabs">
				<div id="horizontalTab" style="display: block; width: 100%; margin: 0px;">
					<ul class="resp-tabs-list">
						<li class="resp-tab-item" aria-controls="tab_item-0" role="tab"><span>Login</span></li>
						<!-- <li class="resp-tab-item" aria-controls="tab_item-1" role="tab"><label>/</label><span>Sign up</span></li> -->
						<div class="clearfix"></div>
					</ul>
					<div class="resp-tabs-container">
						<div class="tab-1 resp-tab-content" aria-labelledby="tab_item-0">
							<div class="login-top">
                <?php echo $this->layout()->content; ?>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="logo">
			<div class="logo-top">
      <a id="announce" target=_blank>
				<img id="announce-img">
      </a>
      <a id="announce-qmanager" target=_blank>
				<img id="announce-login">
      </a>
			</div>
		</div>
		<div class="clear"></div>
	</div>
	<div class="account">
			<ul>
				<li><p>Don't have an <a href="#">account?</a> / Forgot <a href="#">password?</a></p></li>
				<div class="clear"></div>
			</ul>
		</div>
	<div class="footer">
		<p>Powered by <a href="https://www.opens.com.br" target="_blank">Opens Tecnologia</a> </p>
	</div>
</body>
</html>
