<?php
$this->headScript()->appendFile($this->baseUrl() .  "/includes/javascript/snep.js");
?>
<script src="/snep/includes/javascript/simpleplayer.js" type="text/javascript"></script>

<div class= "row">
  <div class="tab-content">
    <div class="tab-pane active" id="demo">
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="snep-body-top-buttons">
            <a class="btn btn-add" href="<?php echo $this->url ?>/add/ " role="button"><?php echo $this->translate("Add Sound File")?></a>
            <a class="btn btn-outline btn-add" href="<?php echo $this->url ?>/synchronize/ " role="button"><?php echo $this->translate("Synchronize archives")?></a>
            <div class="snep-body-search">
              <?php if($this->key){ ?>
                <a class='sn-dash-add' href="<?php echo $this->baseUrl ?>/default/index/index?dashboard_add=<?php echo $this->key ?>" title="<?php echo $this->translate('Add to dashboard');?>"></a>
              <?php } ?>
            </div>
          </div>
        </div><br>
        <table class="table table-striped" id="listtable">
          <thead>
            <tr>
              <th class="text-center"><?php echo $this->translate('Filename') ?> </th>
              <th class="text-center"><?php echo $this->translate('Description') ?> </th>
              <th class="text-center"><?php echo $this->translate('File') ?> </th>
              <th class="text-center"><?php echo $this->translate('Backup') ?> </th>
              <th class="text-center"><?php echo $this->translate('Actions') ?> </th>
            </tr>
          </thead>
          <tbody>
            <?php if ($this->files):
              foreach ($this->files as $file): ?>
                <tr>
                  <td class="text-center"><?php echo $file['arquivo'] ?></td>
                  <td class="text-center"><?php echo $file['descricao'] ?> </td>
                  <td class="text-center sound-file-player" >
                    <?php $fullpath = ( isset($file['fullpath']) ? $file['fullpath'] : false );
                    if ($fullpath != '') : ?>
                      <audio  class="player" src='<?php echo $fullpath;?>' type="audio/mpeg"  title="<?php echo $this->translate('Listen');?>" preload="none">
                        <?php echo $this->translate('Your browser does not support the audio element.') ?>
                      </audio>
                    <?php else : ?>
                      <span class="sn-sound-off snep-list-sounds"></span>
                    <?php endif ?>
                  </td>
                  <td class="text-center sound-file-player">
                    <?php $backuppath = ( isset($file['backuppath']) ? $file['backuppath'] : false );
                      if ($backuppath != '') : ?>
                        <audio class="player" src='<?php echo $backuppath;?>' type="audio/mpeg"  title="<?php echo $this->translate('Listen');?>">
                          <?php echo $this->translate('Your browser does not support the audio element.') ?>
                        </audio>
                      <?php else : ?>
                        <span class="sn-sound-off snep-list-sounds" title="<?php echo $this->translate('Backp not available');?>"></span>
                      <?php endif ?>
                    </td>
                    <td align="center">
                      <?php if (isset($file['backuppath'])) : ?>
                        <a class="btn btn-success btn-sm" href="<?php echo $this->url ?>/restore/arquivo/<?php echo $file['arquivo'] ?>" role="button" title="<?php echo $this->translate('Restore backup sound file');?>" >
                          <?php echo $this->translate('Restore')?>
                        </a>
                      <?php else : ?>
                        <span class="sn-no-backup snep-list-sounds" title="<?php echo $this->translate('No files to restore');?>"></span>
                      <?php endif ?>
                      <a class="btn btn-edit btn-sm"  href="<?php echo $this->url ?>/edit/arquivo/<?php echo $file['arquivo'] ?>" role="button"><?php echo $this->translate('Edit')?></a>
                      <a class="btn btn-danger btn-sm"  role="button" href="<?php echo $this->url ?>/remove/arquivo/<?php echo $file['arquivo'] ?>"><?php echo $this->translate('Delete') ?></a>
                    </td>
                  </tr>
                <?php endforeach ?>
              <?php endif ?>
            </tbody>
          </table>
        </div>
      </div>
    </div>
</div>

<script type="text/javascript">
jQuery.noConflict();
jQuery(document).ready(function() {
  jQuery('#listtable').dataTable( {
    "pageLength": <?php echo $this->lineNumber ?>,
    "oLanguage": {
      "sUrl": "/snep/includes/javascript/datatables/media/language/pt-BR.json"
    },
    "bLengthChange": false,
  });
});

jQuery(document).ready(function() {
    var settings = {
        progressbarWidth: '60px',
        progressbarHeight: '5px',
        progressbarColor: '#959595',
        progressbarBGColor: '#ebecee',
        defaultVolume: 0.8
    };
    jQuery(".player").player(settings);
});
</script>



