<?php
$this->headLink()->appendStylesheet( $this->baseUrl() . "/css/index.css" );
$this->headScript()->appendFile( $this->baseUrl() . '/includes/javascript/scriptaculous/lib/prototype.js');

?>
<form  action="<?php echo $this->url(array("controller" => "queues-groups", "action" => "members"), null, true); ?>" METHOD="post">

<table>
    <thead>
        <tr>
            <th> <?php echo $this->translate('Queue') ?> </th>
            <th> <?php echo$this->translate('Member') ?> </th>
            <th colspan="2" class="action"> <?php echo $this->translate('Actions') ?> </th>
        </tr>
    </thead>
   
    <tbody>
    

    <?php
    $c = 0;
    $enabled = '<img src="/snep/images/true.png" align="center" width="15" height="15" title="Sim";">';
    $disabled = '<img src="/snep/images/false.png" width="15" height="15" title="Não";">';
    
    if($this->queues){
        foreach($this->queues as $cha => $queue ):?> 
            		
            <?php ($c ? $c = 0 : $c = 1 ); ?>
            <tr class="c<?php echo $c ?>">
                <td> 
                    <?php echo $queue['name']; ?>
                </td>
                <?php if(isset($queue['belongs'])){ ?>
                <td> <?php echo $enabled ?> </td>
                <td> <input name=<?php echo $queue['id'] ?> type="checkbox" value="yes" checked><?php echo $this->translate('Member') ?><br></td>
                <?php }else{ ?>
                <td> <?php echo $disabled ?> </td>
                <td> <input name=<?php echo $queue['id'] ?> type="checkbox" value="yes"><?php echo $this->translate('Member') ?><br></td>
                <?php } ?>

                <input type="hidden" name="id_group" value=<?php echo $this->id ?>>           
            </tr>
            
        <?php endforeach ?>
    <?php }else{ ?>

    <?php } ?>
</table>


<div class="permission">
        <dt></dt>
        <dd><input type="submit" value="<?php echo $this->translate("Save"); ?>" /></dd>
</div>
</form>
