    
<div id="containerStatus">
    <div id="statusTopo">
        <div class="expand">
            <a href="#"><?php echo $this->translate("Services"); ?></a>
        </div>
        <div>
            <ul>
                <li>
                    <?php
                    if ($this->indexData["asterisk"] != "Asterisk - "){
                        echo "<div class='statusIndicator green'></div>";
                    }else{
                        echo "<div class='statusIndicator red'></div>";
                    }
                    ?><span>Asterisk</span>
                </li>
                
                <li>
                    <?php
                    if ($this->indexData["usage"] <= 50){
                        echo "<div class='statusIndicator green'></div>";
                    }else if ($this->indexData["usage"] > 50 && $this->indexData["usage"] <= 80){
                        echo "<div class='statusIndicator yellow'></div>";
                    }else{
                        echo "<div class='statusIndicator red'></div>";
                    }
                    ?><span><?php echo $this->translate("CPU"); ?></span> <?php echo $this->indexData["usage"] . '%'; ?>
                </li>
                <li>
                    <?php
                    if ($this->indexData["memory"]['ram']["percent"] <= 50){
                        echo "<div class='statusIndicator green'></div>";
                    }else if ($this->indexData["memory"]['ram']["percent"] > 50 && $this->indexData["memory"]['ram']["percent"] <= 80){
                        echo "<div class='statusIndicator yellow'></div>";
                    }else{
                        echo "<div class='statusIndicator red'></div>";
                    }
                    ?>
                    <span><?php echo $this->translate("Fisical Memory"); ?></span> <?php echo $this->indexData["memory"]['ram']["percent"] . '%'; ?>
                </li>
                <li>
                    <?php
                    foreach ($this->indexData["space"] as $key => $value){
                        if (!isset($maior) || $value["percent"] > $maior["percent"]){
                            $maior = $value;
                        }
                    }
                    if ($maior["percent"] <= 50){
                        echo "<div class='statusIndicator green'></div>";
                    }else if ($maior["percent"] > 50 && $maior["percent"] <= 80){
                        echo "<div class='statusIndicator yellow'></div>";
                    }else{
                        echo "<div class='statusIndicator red'></div>";
                    }
                    ?>
                    <span><?php echo $this->translate("Disk Usage"); ?></span> <?php echo $maior["percent"].'%'; ?>
                </li>
            </ul>
        </div>
        <div class="version">
                <?php echo SNEP_VENDOR; ?> - <?php echo $this->translate("SNEP Version"); ?> <?php echo SNEP_VERSION?> 
        </div>
    </div>
    
    <?php if ($this->error) : ?>
        <div class="error_box" >
            <?php echo $this->translate("Errors were detected in the configuration of SNEP, click "); ?>
            <a href="<?php echo $this->inspector; ?>">
                <?php echo $this->translate("here"); ?>
            </a>
            <?php echo $this->translate(" for more information"); ?>
        </div>
    <?php endif ?>
    
    <div id="statusBody">
        <div class="statusColumn">
            <div class="statusBlock">
                <div class="iconHolder">
                    <img alt="" src="<?php echo $this->baseUrl(); ?>/modules/default/img/system_status_icon_status_bar.png">
                </div>
                <div class="contentHolder">
                    <h2> <?php echo $this->translate("Server Status"); ?></h2>
                    <table>
                        <tr>
                            <th><?php echo $this->translate("Distribution"); ?></th>
                            <td> <?php echo $this->indexData["linux_ver"]; ?></td>
                        </tr>
                    </table>
                    
                    <table>
                    <tr>
                        <th><?php echo $this->translate("Kernel"); ?></th>
                        <td> <?php echo $this->indexData['linux_kernel']; ?></td>
                    </tr>
                    </table>

                    <table>
                        <tr>
                            <th><?php echo $this->translate("CPU"); ?></th>
                            <td> <?php echo $this->indexData["hardware"]; ?></td>
                        </tr>
                    </table>

                    <table>
                        <tr>
                            <th><?php echo $this->translate("Uptime"); ?></th>
                            <td> <?php echo $this->indexData["uptime"]; ?></td>
                        </tr>
                    </table>

                    <table>
                        <tr>
                            <th><?php echo $this->translate("Asterisk"); ?></th>
                            <td> <?php echo $this->indexData["asterisk"]; ?></td>
                        </tr>
                    </table>

                    <table>
                        <tr>
                            <th><?php echo $this->translate("MySQL"); ?></th>
                            <td> <?php echo $this->indexData["mysql"]; ?></td>
                        </tr>
                    </table>

                </div>
            </div>
            <div class="statusBlock">
                <div class="iconHolder">
                    <img alt="" src="<?php echo $this->baseUrl(); ?>/modules/default/img/modules_icon_status_bar.png">
                </div>
                <div class="contentHolder">
                    <h2><?php echo $this->translate("Modules"); ?></h2>
                    <?php
                    if (count($this->indexData["modules"]) > 0) {
                        foreach ($this->indexData["modules"] as $key => $value) {
                            ?>
                            <table>
                                <tr>
                                    <th><?php echo $this->translate($value['name'])." - "; echo $this->translate($value['version']); ?></td>
                                    <td> <?php echo $this->translate($value['description']); ?></td>
                                </tr>
                            </table>
                        <?php
                        }
                    }else{
                        ?>
                        <p><?php echo $this->translate("No modules instaled."); ?></p>
                    <?php 
                    }
                    ?>
                </div>
            </div>
            
        </div>
        <div class="statusColumn">
            <div class="statusBlock">
                <div class="iconHolder">
                    <img alt="" src="<?php echo $this->baseUrl(); ?>/modules/default/img/memory_icon_status_bar.png">
                </div>
                <div class="contentHolder">
                    <h2><?php echo $this->translate("Memory Usage"); ?></h2>
                    <table>
                        <tr>
                            <th><?php echo $this->translate("Type"); ?></th>
                            <th><?php echo $this->translate("Total"); ?></th>
                            <th><?php echo $this->translate("Free"); ?></th>
                            <th><?php echo $this->translate("Used"); ?></th>
                        </tr>
                        <tr>
                            <th style="text-align: left;"><?php echo $this->translate("Fisical Memory"); ?></th>
                            <td style="text-align: left;"><?php echo $this->indexData["memory"]['ram']["total"]; ?></td>
                            <td style="text-align: left;"><?php echo $this->indexData["memory"]['ram']["free"]; ?></td>
                            <td style="text-align: left;" class="graphBar">
                                <div class="bar_chart">
                                    <?php 
                                    $classColor = '';
                                    if ($this->indexData["memory"]['ram']["percent"] <= 50){
                                        $classColor = "bar_color_green";
                                    }
                                    else if ($this->indexData["memory"]['ram']["percent"] > 50 && $this->indexData["memory"]['ram']["percent"] <= 80){
                                        $classColor = "bar_color_yellow";
                                    }
                                    else{
                                        $classColor = "bar_color_red ";
                                    }
                                    ?>
                                    <div class="bar_inner <?php echo $classColor; ?>"  style="width:  <?php echo $this->indexData["memory"]['ram']["percent"] . '%'; ?>;">
                                        <div class="bar_text">
                                            <?php echo $this->indexData["memory"]['ram']["percent"] . '%'; ?>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <th><?php echo $this->translate(" -Kernel + Aplic."); ?></th>
                            <td style="text-align: left;"><?php echo $this->indexData["memory"]['ram']["app"]; ?></td>
                            <td style="text-align: left;"></td>
                            <td style="text-align: left;" class="graphBar">
                                <div class="bar_chart">
                                    <?php 
                                    $classColor = '';
                                    if ($this->indexData["memory"]['ram']["app_percent"] <= 50){
                                        $classColor = "bar_color_green";
                                    }
                                    else if ($this->indexData["memory"]['ram']["app_percent"] > 50 && $this->indexData["memory"]['ram']["app_percent"] <= 80){
                                        $classColor = "bar_color_yellow";
                                    }
                                    else{
                                        $classColor = "bar_color_red ";
                                    }
                                    ?>
                                    <div class="bar_inner <?php echo $classColor; ?>"  style="width:  <?php echo $this->indexData["memory"]['ram']["app_percent"] . '%'; ?>;">
                                        <div class="bar_text">
                                            <?php echo $this->indexData["memory"]['ram']["app_percent"] . '%'; ?>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                         <tr>
                            <th style="text-align: left;" ><?php echo $this->translate("Buffers"); ?></th>
                            <td style="text-align: left;" ></td>
                            <td style="text-align: left;" ></td>
                            <td style="text-align: left;" class="graphBar">
                                <div class="bar_chart">
                                    <?php 
                                    $classColor = '';
                                    if ($this->indexData["memory"]['ram']["buffers_percent"] <= 50){
                                        $classColor = "bar_color_green";
                                    }
                                    else if ($this->indexData["memory"]['ram']["buffers_percent"] > 50 && $this->indexData["memory"]['ram']["buffers_percent"] <= 80){
                                        $classColor = "bar_color_yellow";
                                    }
                                    else{
                                        $classColor = "bar_color_red ";
                                    }
                                    ?>
                                    <div class="bar_inner <?php echo $classColor; ?>"  style="width:  <?php echo $this->indexData["memory"]['ram']["buffers_percent"] . '%'; ?>;">
                                        <div class="bar_text">
                                            <?php echo $this->indexData["memory"]['ram']["buffers_percent"] . '%'; ?>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                         <tr>
                            <th><?php echo $this->translate("Cached"); ?></th>
                            <td style="text-align: left;" ></td>
                            <td style="text-align: left;" ></td>
                            <td  style="text-align: left;" class="graphBar">
                                <div class="bar_chart">
                                    <?php 
                                    $classColor = '';
                                    if ($this->indexData["memory"]['ram']["cached_percent"] <= 50){
                                        $classColor = "bar_color_green";
                                    }
                                    else if ($this->indexData["memory"]['ram']["cached_percent"] > 50 && $this->indexData["memory"]['ram']["cached_percent"] <= 80){
                                        $classColor = "bar_color_yellow";
                                    }
                                    else{
                                        $classColor = "bar_color_red ";
                                    }
                                    ?>
                                    <div class="bar_inner <?php echo $classColor; ?>"  style="width:  <?php echo $this->indexData["memory"]['ram']["cached_percent"] . '%'; ?>;">
                                        <div class="bar_text">
                                            <?php echo $this->indexData["memory"]['ram']["cached_percent"] . '%'; ?>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <th><?php echo $this->translate("Swap Memory"); ?></th>
                            <td style="text-align: left;" ><?php echo $this->indexData["memory"]['swap']["total"]; ?></td>
                            <td style="text-align: left;" ><?php echo $this->indexData["memory"]['swap']["free"] ; ?></td>
                            <td  style="text-align: left;" class="graphBar">
                            <div class="bar_chart">
                                    <?php 
                                    $classColor = '';
                                    if ($this->indexData["memory"]['swap']["percent"] <= 50){
                                        $classColor = "bar_color_green";
                                    }
                                    else if ($this->indexData["memory"]['swap']["percent"] > 50 && $this->indexData["memory"]['swap']["percent"] <= 80){
                                        $classColor = "bar_color_yellow";
                                    }
                                    else{
                                        $classColor = "bar_color_red ";
                                    }
                                    ?>
                                    <div class="bar_inner <?php echo $classColor; ?>"  style="width: <?php echo $this->indexData["memory"]['swap']["percent"]. '%'; ?>;">
                                        <div class="bar_text">
                                            <?php echo $this->indexData["memory"]['swap']["percent"] . '%'; ?>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>

            <div class="statusBlock">
                <div class="iconHolder">
                    <img alt="" src="<?php echo $this->baseUrl(); ?>/modules/default/img/drive_space_status.png">
                </div>
                <div class="contentHolder">
                    <h2><?php echo $this->translate("Disk Usage"); ?></h2>
                    <table>
                        <tr>
                            <th style="text-align: left;" ><?php echo $this->translate("Partition"); ?></th>
                            <th style="text-align: left;" ><?php echo $this->translate("Size"); ?></th>
                            <th style="text-align: left;" ><?php echo $this->translate("Free"); ?></th>
                            <th style="text-align: left;" ><?php echo $this->translate("Used"); ?></th>
                        </tr>
                        <?php
                        foreach ($this->indexData["space"] as $key => $value) {
                            ?>             

                            <tr>
                                <th style="text-align: left;" ><?php echo $value["mount_point"]; ?></th>
                                <td style="text-align: left;" ><?php echo $value["size"]; ?></td>
                                <td  style="text-align: left;" ><?php echo $value["free"]; ?></td>
                                <td style="text-align: left;"  class="graphBar">
                                    <div class="bar_chart">
                                        <?php 
                                        if ($value["percent"] <= 50){
                                            $classColor = "bar_color_green";
                                        }
                                        else if ($value["percent"] > 50 && $value["percent"] <= 80){
                                            $classColor = "bar_color_yellow";
                                        }
                                        else{
                                            $classColor = "bar_color_red ";
                                        }
                                        ?>
                                        <div class="bar_inner <?php echo $classColor; ?>"  style="width: <?php echo $value["percent"].'%'; ?>;">
                                            <div class="bar_text">
                                                <?php echo $value["percent"].'%'; ?>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr> 

                        <?php } ?>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


