<div class="row">           
    <form id="defaultForm" method="post" class="form-horizontal" action="<?php echo $this->url(array("controller" => "users", "action" => $this->action), null, false); ?>" METHOD="post">
        
        <div class="form-group">
            <label class="col-sm-2 control-label"><?php echo $this->translate("Username");?></label>
            <div class="col-sm-4">
                <input type="text" class="form-control" name="name" placeholder='<?php echo $this->translate("Name")?>' value="<?php echo $this->user['name']; ?>" />
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label"><?php echo $this->translate("Password");?></label>
            <div class="col-sm-4">
                <input type="password" class="form-control" name="password" placeholder='<?php echo $this->translate("Minimum 5 characters")?>' value="<?php echo $this->user['password']; ?>"/>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label"><?php echo $this->translate("Email address");?></label>
            <div class="col-sm-6">
                <input type="text" class="form-control" name="email" value="<?php echo $this->user['email']; ?>"/>
            </div>
        </div>

        <div class="form-group">
        	<label class="col-sm-2 control-label"><?php echo $this->translate("Profile");?></label>
        	<div class="col-sm-6">
        		<select class="form-control" name="group" id="group" value="<?php echo $this->user['groupname']; ?>">
        			<?php foreach($this->profiles as $key => $profile){ ?>
			    		<option <?php echo $profile['selected'];?>>
                            <?php echo $profile['name'];?>
                        </option>
			    	<?php } ?>
				</select>
			</div>
		</div>
        
        <div class="snep-body-footer-buttons">
                <button type="submit" class="btn btn-add" name="save" value="save"><?php echo $this->translate("Save");?></button>
                &nbsp;&nbsp;&nbsp;
            	<a class="btn btn-outline btn-add" href="javascript:window.history.go(-1)" role="button"><?php echo $this->translate("Cancel")?></a>
        </div>
    </form>
</div>

<script type="text/javascript">

jQuery.noConflict();
jQuery(document).ready(function(){ 
    jQuery('#defaultForm').validate({
        rules: {
            name: {
                required: true,
                minlength: 5,
                maxlength: 30
            },
            password: {
                required: true,
                minlength: 5,
                maxlength: 32,
            },
            email: {
                required: true,
                email: true
            }
        },
        messages: {
            name: {
                required: "<?php echo $this->translate('The username is required'); ?>",
                minlength: "<?php echo $this->translate('Please enter at least {0} characters.'); ?>", 
                maxlength: "<?php echo $this->translate('Please enter no more than {0} characters.'); ?>",
                lettersOnly: "<?php echo $this->translate('Letters only please'); ?>" 
            },
            password: {
                required: "<?php echo $this->translate('The password is required'); ?>",
                minlength: "<?php echo $this->translate('Please enter at least {0} characters.'); ?>", 
                maxlength: "<?php echo $this->translate('Please enter no more than {0} characters.'); ?>"
            },
            email: {
                required: "<?php echo $this->translate('The e-mail is required'); ?>",
                email: "<?php echo $this->translate('Your email address must be in the format of name@domain.com'); ?>"
            }
        },
        highlight: function(element) {
            jQuery(element).closest('.control-group').removeClass('success').addClass('error');
        },
        success: function(element) {
            element
            .text('OK!').addClass('valid')
            .closest('.control-group').removeClass('error').addClass('success');
        }
    });
}); 
</script>




