<?php

/*
 *  This file is part of SNEP.
 *
 *  SNEP is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  SNEP is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with SNEP.  If not, see <http://www.gnu.org/licenses/>.
 */
$this->headLink()->appendStylesheet( $this->baseUrl() . "/css/bootstrap-select.css" );
$this->headScript()->appendFile($this->baseUrl() . "/includes/javascript/password.js");
?>
<script src="/snep/includes/javascript/password.js"></script>
<script src="/snep/includes/javascript/bootstrap-select.js"></script>
<div class="row">
    <form id="defaultForm" method="post" class="form-horizontal" action="<?php echo $this->url(array("controller" => "users", "action" => $this->action), null, false); ?>" autocomplete="off">

        <div class="form-group">
            <label class="col-sm-2 control-label"><?php echo $this->translate("Username");?></label>
            <div class="col-sm-4">
                <input type="text" class="form-control" name="name" placeholder='<?php echo $this->translate("Name")?>' value="<?php echo $this->user['name']; ?>"  <?php echo $this->action === 'edit' ? 'readonly' : '';?> />
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label"><?php echo $this->translate("Password");?></label>
            <div class="col-sm-4">
                <input type="password" class="form-control" name="password" id="password" placeholder='<?php echo $this->translate("Minimum 5 characters")?>' value="<?php echo $this->user['password']; ?>"/>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label"><?php echo $this->translate("Email address");?></label>
            <div class="col-sm-6">
                <input type="text" class="form-control" name="email" value="<?php echo $this->user['email']; ?>"/>
            </div>
        </div>

        <div class="form-group">
        	<label class="col-sm-2 control-label"><?php echo $this->translate("Profile");?></label>
        	<div class="col-sm-6">
        		<select class="form-control" name="profile_id" id="group" value="<?php echo $this->user['groupname']; ?>">
        			<?php foreach($this->profiles as $key => $value){
                        $selected = $value['id'] === $this->user['profile_id'] ? "selected" : "" ; ?>
			    		<option value="<?php echo $value['id'];?>" <?php echo $selected;?>>
                            <?php echo $value['name'];?>
                        </option>
			    	<?php } ?>
				</select>
			</div>
		</div>

        <?php if ($this->user['id'] != "1") { ?>
            <div class="form-group">
                <label class="col-sm-2 control-label"><?php echo $this->translate("Queue visualization");?></label>
                    <div class="col-sm-6">
                        <select class="form-control selectpicker <?php echo $this->classQueue ?>" multiple name="queues[]" id="queues[]">
                        <?php foreach($this->queues as $key => $queue){ ?>
                                <?php if(isset($queue['selected'])){ ?>
                                    <option value='<?php echo $queue['id']?>' selected><?php echo $queue['name'];?></option>
                                <?php }else{ ?>
                                    <option value='<?php echo $queue['id']?>'><?php echo $queue['name'];?></option>
                                <?php }?>
                            <?php }?>
                        </select>
                    </div>
                </div>
            </div>
        <?php } ?>

        <div class="snep-body-footer-buttons">
                <button type="submit" class="btn btn-add" name="save" value="save"><?php echo $this->translate("Save");?></button>
                &nbsp;&nbsp;&nbsp;
            	<a class="btn btn-outline btn-add" href="javascript:window.history.go(-1)" role="button"><?php echo $this->translate("Cancel")?></a>
        </div>
    </form>
</div>

<script type="text/javascript">

jQuery.noConflict();
jQuery(document).ready(function(){
    jQuery('#defaultForm').validate({
        rules: {
            name: {
                required: true,
                minlength: 5,
                maxlength: 30
            },
            password: {
                required: true,
                minlength: 5,
                maxlength: 32,
            },
            email: {
                required: true,
                email: true
            }
        },
        messages: {
            name: {
                required: "<?php echo $this->translate('The username is required'); ?>",
                minlength: "<?php echo $this->translate('Please enter at least {0} characters.'); ?>",
                maxlength: "<?php echo $this->translate('Please enter no more than {0} characters.'); ?>",
                lettersOnly: "<?php echo $this->translate('Letters only please'); ?>"
            },
            password: {
                required: "<?php echo $this->translate('The password is required'); ?>",
                minlength: "<?php echo $this->translate('Please enter at least {0} characters.'); ?>",
                maxlength: "<?php echo $this->translate('Please enter no more than {0} characters.'); ?>"
            },
            email: {
                required: "<?php echo $this->translate('The e-mail is required'); ?>",
                email: "<?php echo $this->translate('Your email address must be in the format of name@domain.com'); ?>"
            }
        },
        highlight: function(element) {
            jQuery(element).closest('.control-group').removeClass('success').addClass('error');
        },
        success: function(element) {
            element
            .text('OK!').addClass('valid')
            .closest('.control-group').removeClass('error').addClass('success');
        }
    });

    <?php if ($this->action === 'add') { ?>

        jQuery(function() {

            jQuery('#password').password().on('show.bs.password', function(e) {

                jQuery('#methods').prop('checked', true);

                }).on('hide.bs.password', function(e) {
                    jQuery('#methods').prop('checked', false);
                });
                jQuery('#methods').click(function() {
                    jQuery('#password').password('toggle');
                });
            });
    <?php }?>
</script>
