<?php
$this->headLink()->appendStylesheet( $this->baseUrl() . "/css/footable/footable.core.css" );
$this->headLink()->appendStylesheet( $this->baseUrl() . "/css/footable/footable-demos.css" );
$this->headLink()->appendStylesheet( $this->baseUrl() . "/css/footable/bootstrap-glyphicons.css" );
?>

<script src="/snep/includes/javascript/footable/footable.js" type="text/javascript"></script>
<script src="/snep/includes/javascript/footable/footable.sort.js" type="text/javascript"></script>
<script src="/snep/includes/javascript/footable/footable.filter.js" type="text/javascript"></script>
<script src="/snep/includes/javascript/footable/footable.paginate.js" type="text/javascript"></script>
<script src="/snep/includes/javascript/footable/bootstrap-tab.js" type="text/javascript"></script>

<div class= "row">
    <div class="tab-content">
        <div class="tab-pane active" id="demo">
            <div class="panel panel-default">
                <div class="panel-heading">

                    <div class="snep-body-top-buttons">
                        <a class="btn btn-add" href="<?php echo $this->url ?>/add/ " role="button"><?php echo $this->translate("Add User")?></a>

                        <div class="snep-body-search">

                            <?php if($this->key){ ?>
                                <a class='sn-dash-add' href="<?php echo $this->baseUrl ?>/default/index/index?dashboard_add=<?php echo $this->key ?>" title="<?php echo $this->translate('Add to dashboard');?>">
                                </a>
                                &nbsp;|&nbsp;
                            <?php } ?>
                            <?php echo $this->translate("Search")?>
                            <a class="filter"><input id="filter" type="text"/></a>
                        </div>
                    </div>
                </div>

                <table class="table demo table-hover" data-filter="#filter" data-page-size="<?php echo $this->lineNumber?>">

                    <thead>

                        <tr>
                            <th class="text-center" data-type="numeric" data-sort-initial="true"><?php echo $this->translate('Code');?></th>
                            <th><?php echo $this->translate('Name');?></th>
                            <th class="text-center"><?php echo $this->translate('Created');?></th>
                            <th class="text-center"><?php echo $this->translate('Updated');?></th>
                            <th class="text-center"><?php echo $this->translate('Profile');?></th>
                            <th colspan="4" class="text-center" data-sort-ignore="true"><?php echo $this->translate('Actions');?></th>
                        </tr>
                    </thead>
                    <tbody>

                        <?php if ($this->users):
                            foreach ($this->users as $user): ?>

                                <tr>
                                    <td  class="text-center"> <b> <?php echo $user['ide'] ?> </b> </td>
                                    <td> <?php echo $user['nome'] ?> </td>
                                    <td class="text-center"> <?php echo date('d/m/Y H:i:s', strtotime($user['created'])) ?> </td>
                                    <td class="text-center"> <?php echo date('d/m/Y H:i:s', strtotime($user['updated'])) ?> </td>
                                    <td class="text-center"> <?php echo $user['name'] ?> </td>

                                    <?php if ($user['ide'] == "1") {
                                        $disabled= "disabled";
                                    }else{
                                        $disabled = "";
                                    }?>

                                    <td align="center">
                                        <a class="btn btn-default btn-sm <?php echo $disabled ?>"  href="<?php echo $this->url ?>/permission/id/<?php echo $user['ide'] ?>" role="button"><?php echo $this->translate('Permission')?></a>
                                        <a class="btn btn-default btn-sm <?php echo $disabled ?>"  href="<?php echo $this->url ?>/bond/id/<?php echo $user['ide'] ?>" role="button"><?php echo $this->translate('Bond')?></a>
                                        <a class="btn btn-edit btn-sm" href="<?php echo $this->url ?>/edit/id/<?php echo $user['ide'] ?>" role="button"><?php echo $this->translate('Edit')?></a>
                                        <a class="btn btn-danger btn-sm <?php echo $disabled ?>" href="<?php echo $this->url ?>/remove/id/<?php echo $user['ide'] ?>" role="button"><?php echo $this->translate('Delete')?></a>
                                    </td>
                                </tr>
                            <?php endforeach ?>
                        <?php endif ?>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="9">
                                <div class="paging">
                                    <ul class="pagination"></ul>
                                </div>
                            </td>

                        </tr>
                    </tfoot>
                </table>
            </div>
        </div> <!-- demo -->
    </div> <!-- tab-content -->
</div> <!-- /.row -->

<script type="text/javascript">
    jQuery.noConflict();
    jQuery(function () {
        jQuery('table').footable().on('click', '.row', function(e) {
            e.preventDefault();
        });
    });
</script>

