<?php
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/add.css");
$this->headScript()->appendFile($this->baseUrl() . '/includes/javascript/scriptaculous/lib/prototype.js');
$this->headScript()->appendFile($this->baseUrl() . '/includes/javascript/selectBox.js');
$this->headScript()->appendFile($this->baseUrl() . "/includes/javascript/scriptaculous/src/scriptaculous.js", 'text/javascript');
$this->headScript()->appendFile($this->baseUrl() . '/includes/lightbox.js', 'text/javascript');
?>

<div id="lightboxbody">
    <a id="lightboxLink" href="javascript:void(0);"><img src="/snep/imagens/help.png" class="right"></a>
</div>

<div id="containerDiv">
    <h2><?php echo $this->translate("Operadoras - Incluir"); ?></h2>

    <?php echo $this->translate("Esta rotina permite que uma Operadora seja Cadastrada no Sistema."); ?>

    <br><strong><?php echo $this->translate("Nome:"); ?></strong>
    <?php echo $this->translate("Define o nome que identificará a Operadora."); ?>

    <br><strong><?php echo $this->translate("Tempo de Arranque:"); ?></strong>
    <?php echo $this->translate("Define o tempo em SEGUNDOS que a 
    Operadora cobra a Tarifa de saída. Normalmente as Operadoras cobram o 
    primeiro minuto cheio (60 segundos) de uma chamada , independente da duração desta."); ?>

    <br><strong><?php echo $this->translate("Valor Controle de Qualidade:"); ?></strong> 
    <?php echo $this->translate("Define o tempo em SEGUNDOS das 
    frações seguintes de incidência da tarifa. Exemplo: o valor é tarifado a 
    cada 6 segundos em 1/10, ou seja, se a tarifa for de R$ 0,50 por minuto, 
    a cada 6 segundos de duração , será cobrado R$ 0,05."); ?>

    <br><strong><?php echo $this->translate("Tarifa para Fixo:"); ?></strong>
    <?php echo $this->translate("Define o valor da Tarifa padrão para chamadas 
    a telefones Fixos."); ?>

    <br><strong><?php echo $this->translate("Tarifa para Celular:"); ?></strong> 
    <?php echo $this->translate("Define o valor da Tarifa padrão para 
    chamadas a telefones Celulares."); ?>

    <br><strong><?php echo $this->translate("Centro de Custos:"); ?></strong> 
    <?php echo $this->translate("Define o(s) Centro(s) de Custo(s) que fazem 
    parte da Operadora. Quando uma chamada é efetuada, um Centro de Custos é 
    definido para esta. Baseado no Centro de Custo defiunido para cada registro 
    de chamada efetuada, o sistema irá encontrar a Operadora e consequentemente 
    o valor da Tarifa."); ?>
    <br>
    <br>
    <a id="closeLink" href="javascript:void(0);"><?php echo $this->translate("Back"); ?></a><br><br>
</div> 

<?php echo $this->form; ?>            

<script type="text/javascript">
    Event.observe(window, 'load', init, false);

    function init() {
        select = new SelectBox('<?php echo $this->objSelectBox ?>');
    }

    var test;

    Event.observe(window, 'load', function() {
        test = new Lightbox('containerDiv');
    });
    Event.observe('lightboxLink', 'click', function() {
        test.open();
    });
    Event.observe('closeLink', 'click', function() {
        test.close();
    });
</script>

