<?php
$this->headLink()->appendStylesheet( $this->baseUrl() . "/css/bootstrap-duallistbox.css" );
?>
<script type="text/javascript" src="/snep/includes/javascript/jquery.bootstrap-duallistbox.js"></script>
	
<div class="row">
                
    <form id="defaultForm" method="post" class="form-horizontal" action="<?php echo $this->url(array("controller" => "contact-groups", "action" => $this->action), null, false); ?>" METHOD="post">

        <div class="form-group">
            <label class="col-sm-2 control-label"><?php echo $this->translate("Name");?></label>
            <div class="col-sm-6">
                <input type="text" class="form-control" name="group" value="<?php echo $this->group;?>" />
            </div>
        </div>

        <select multiple="multiple" size="10" name="duallistbox_group[]" id="select">
            
      	    <?php foreach($this->noGroupContacts as $y => $noGroupContact){ ?>      
                <option value="<?php echo $y;?>"><?php echo $noGroupContact;?></option>
            <?php }?>
            
            <?php foreach($this->groupContacts as $x => $groupContact){?>
                <option value="<?php echo $x;?>" selected="selected"><?php echo $groupContact;?></option>
            <?php } ?>    
      	    
        </select>	

        
        <br>
        <div class="snep-body-footer-buttons">
            <button type="submit" class="btn btn-add" name="save" value="Save"><?php echo $this->translate("Save");?></button>
            &nbsp;&nbsp;&nbsp;
        	<a class="btn btn-outline btn-add" href="javascript:window.history.go(-1)" role="button"><?php echo $this->translate("Cancel")?></a>

        </div>
    </form>


</div>

<script type="text/javascript">

jQuery.noConflict();
jQuery(document).ready(function(){ 
    jQuery('#defaultForm').validate({
        rules: {
            group: {
                required: true,
                minlength: 5,
                maxlength: 50,
                lettersAndNumbersOnly: true
            }
        },
        messages: {
            group: {
                required: "<?php echo $this->translate('The name is required'); ?>",
                minlength: "<?php echo $this->translate('Please enter at least {0} characters.'); ?>", 
                maxlength: "<?php echo $this->translate('Please enter no more than {0} characters.'); ?>",
                lettersAndNumbersOnly: "<?php echo $this->translate('Please enter letters and numbers only.'); ?>" 
            }
        },
        highlight: function(element) {
            jQuery(element).closest('.control-group').removeClass('success').addClass('error');
        },
        success: function(element) {
            element
            .text('OK!').addClass('valid')
            .closest('.control-group').removeClass('error').addClass('success');
        }
    });
}); 

var profile = jQuery('select[name="duallistbox_group[]"]').bootstrapDualListbox({
    selectedListLabel: "<?php echo $this->translate('Selected'); ?>" ,
    nonSelectedListLabel: "<?php echo $this->translate('Available'); ?>",
    infoText: "<?php echo $this->translate('Showing all '); ?> {0}"
    });
jQuery("#defaultForm").submit(function() {
    return true;
});

</script>