<?php
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/index.css");
$this->headScript()->appendFile($this->baseUrl() . '/includes/javascript/scriptaculous/lib/prototype.js');
$this->headScript()->appendFile($this->baseUrl() . '/includes/javascript/scriptaculous/src/scriptaculous.js');
$this->headScript()->appendFile($this->baseUrl() . '/includes/javascript/removeItem.js');
echo $this->render('filter.phtml')
?>

<table>
    <thead>
        <tr>

            <th class="action"> <?php echo Snep_Order::getLink($this, 'Code', 'id') ?></th>
            <th class="action"> <?php echo Snep_Order::getLink($this, 'Name', 'name') ?></th>
            <th class="action" colspan="2"> 
                <?php echo $this->translate('Actions') ?>
            </th>
        </tr>
    </thead>
    <tbody>
        <?php
        $c = 0;
        if ($this->contactgroups):
            foreach ($this->contactgroups as $group):
                ?>
        <?php ($c ? $c = 0 : $c = 1 ); ?>
                <tr class="c<?php echo $c ?>">
                    <td class="numeric">
                        <b> <?php echo $group['id'] ?> </b>
                    </td>
                    <td> 
        <?php echo $group['name'] ?>
                    </td>
                    <td class="action">
                        <a class="alterar" href="<?php echo $this->url ?>/edit/id/<?php echo $group['id'] ?>">
        <?php echo $this->translate('Edit') ?>
                        </a>
                    </td>
                    <td class="action">
                            <?php if ($group['id'] != 1) { ?>
                            <a class="excluir" href="<?php echo $this->url ?>/remove/id/<?php echo $group['id'] ?>">
                            <?php echo $this->translate('Delete') ?>
                            </a>
        <?php } ?>
                    </td>

                </tr>
            <?php endforeach ?>
<?php endif ?>
</table>

<?php echo $this->render('pagination.phtml') ?>