<?php
$this->headScript()->appendFile('/snep/includes/javascript/enableField.js');
$this->headScript()->appendFile($this->baseUrl() . "/includes/javascript/scriptaculous/src/scriptaculous.js", 'text/javascript');
?>

<?php echo $this->message ?>
<?php echo $this->form ?>

<script language="javascript" type="text/javascript">
    $('option-migrate').observe('click', enable);
    $('option-remove').observe('click', disable);

    Event.observe(window, 'load', init);

    function enable() {
        enableField('option-migrate', 'group');
    }
    function disable() {
        enableField('option-migrate', 'group');
    }
</script>
