<?php
$this->headLink()->appendStylesheet( $this->baseUrl() . "/css/footable/footable.core.css" );
$this->headLink()->appendStylesheet( $this->baseUrl() . "/css/footable/footable-demos.css" );
$this->headLink()->appendStylesheet( $this->baseUrl() . "/css/footable/bootstrap-glyphicons.css" );
?>
<script src="/snep/includes/javascript/footable/footable.js" type="text/javascript"></script>
<script src="/snep/includes/javascript/footable/footable.sort.js" type="text/javascript"></script>
<script src="/snep/includes/javascript/footable/footable.filter.js" type="text/javascript"></script>
<script src="/snep/includes/javascript/footable/footable.paginate.js" type="text/javascript"></script>
<script src="/snep/includes/javascript/footable/bootstrap-tab.js" type="text/javascript"></script>

<div class="row">

    <div class="tab-content">
        <div class="tab-pane active" id="demo">
            
            <form id="defaultForm" method="post" class="form-horizontal" style="margin-top: 20px;" action="<?php echo $this->url(array("controller" => "calls-report", "action" => "view"), null, false); ?>" METHOD="post">
                
                <div class="snep-body-top-buttons">
                    
                    <a class="btn btn-add" href="<?php echo $this->url ?>/csv/ " role="button"><?php echo $this->translate("CSV")?></a>

                    <div class="snep-body-search">
                        <?php echo $this->translate("Search")?> 
                        <a class="filter"><input id="filter" type="text"/></a>
                        <br>
                    </div>
                </div>
                
                <table class="table demo table-bordered" data-filter="#filter" data-page-size="<?php echo $this->lineNumber?>">

                    <thead>

                        <tr>
                            <th data-toggle="true" class="text-center" data-type="numeric" data-sort-initial="true"><?php echo $this->translate("Extension") ?></th>
                            <th data-hide="phone,tablet" class="text-center"><?php echo $this->translate("Date") ?></th>
                            <th data-hide="phone,tablet" class="text-center"><?php echo $this->translate("Service") ?></th>
                            <th class="text-center"><?php echo $this->translate("Status") ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        
                        <?php foreach($this->data as $cha => $val ): ?>

                            <tr>
                                <td> <b> <?php echo $val->peer ?> </b> </td>
                                <td> <?php echo $val->date ?> </td>
                                <td> <?php echo $val->service ?> </td>
                                <td> <?php echo $val->status ?> </td>
                            </tr>
                        <?php endforeach ?>
                        
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="9">
                                <div class="paging">
                                    <ul class="pagination"></ul>
                                </div>
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </form>  
        </div>
    </div>
</div> <!-- /.row -->

<script type="text/javascript">
    jQuery.noConflict();
    jQuery(function () {
        jQuery('table').footable().on('click', '.row', function(e) {
            e.preventDefault(); 
        });
    });
</script>


