<?php
$this->headLink()->appendStylesheet($this->baseUrl() . "/includes/javascript/datatables/media/css/dataTables.bootstrap.css");
$this->headLink()->appendStylesheet($this->baseUrl() . "/includes/javascript/datatables/resources/syntax/shCore.css");
$this->headLink()->appendStylesheet($this->baseUrl() . "/includes/javascript/datatables/media/css/buttons.dataTables.css");
$this->headLink()->appendStylesheet($this->baseUrl() . "/includes/javascript/datatables/resources/demo.css");
$this->headScript()->appendFile($this->baseUrl() . "/includes/javascript/snep.js");
?>

<script src="/snep/includes/javascript/datatables/media/js/jquery.dataTables.js" type="text/javascript"></script>
<script src="/snep/includes/javascript/datatables/media/js/dataTables.bootstrap.js" type="text/javascript"></script>
<script src="/snep/includes/javascript/datatables/resources/syntax/shCore.js" type="text/javascript"></script>
<script src="/snep/includes/javascript/datatables/resources/demo.js" type="text/javascript"></script>
<script src="/snep/includes/javascript/datatables/datatables.net-buttons/js/dataTables.buttons.min.js" type="text/javascript"></script>
<script src="/snep/includes/javascript/datatables/media/js/jszip.min.js" type="text/javascript"></script>
<script src="/snep/includes/javascript/datatables/pdfmake/pdfmake.min.js" type="text/javascript"></script>
<script src="/snep/includes/javascript/datatables/pdfmake/vfs_fonts.js" type="text/javascript"></script>
<script src="/snep/includes/javascript/datatables/datatables.net-buttons/js/buttons.html5.min.js" type="text/javascript"></script>

<div class="row">
  <div class="tab-content">
    <div class="tab-pane active" id="demo">
      <table class="table table-striped" id="services">
        <thead>
          <tr>
            <th class="text-center"><?php echo $this->translate("Extension") ?></th>
            <th class="text-center"><?php echo $this->translate("Date") ?></th>
            <th class="text-center"><?php echo $this->translate("Service") ?></th>
            <th class="text-center"><?php echo $this->translate("Status") ?></th>
          </tr>
        </thead>
        <tbody class="table-data">
          <?php foreach ($this->data as $cha => $val): ?>
            <tr>
              <td class="text-center"> <b> <?php echo $val['peer'] ?> </b> </td>
              <td class="text-center"> <?php echo date('d/m/Y H:i:s', strtotime($val['date'])) ?> </td>
              <td class="text-center"> <?php echo $val['service'] ?> </td>
              <td class="text-center"> <?php echo $val['status'] ?> </td>
            </tr>
          <?php endforeach?>
        </tbody>
      </table>
    </div>
  </div>
</div> <!-- /.row -->

<script type="text/javascript">

jQuery.noConflict();

jQuery(document).ready(function() {
  jQuery('#services').dataTable( {
    "pageLength": <?php echo $this->lineNumber ?>,
    "ordering": false,
    "oLanguage": {
      "sUrl": "/snep/includes/javascript/datatables/media/language/pt-BR.json"
    },
    dom: 'Bfrtip',
    buttons: [
      {
        extend: 'excelHtml5',
        title : "SNEP - Relatório de Serviços - <?php echo $this->exportName ?>"
      },
      {
        extend: 'csvHtml5',
        title : "SNEP - Relatório de Serviços - <?php echo $this->exportName ?>"
      },
      {
        extend: 'pdfHtml5',
        title : "SNEP - Relatório de Serviços - <?php echo $this->exportName ?>"
      }
    ]
  });
});

</script>