<div class="row">
        
    <?php
    foreach( $this->inspect as $key => $value ) {
        if ($value['error']) { ?>

            <div class="col-sm-12">
                <div class="panel panel-red">
                    <div class="panel-heading">
                        <?php echo $value['name'];?>
                    </div>
                    <div class="panel-body">
                        <pre><?php echo $value['message'];?></pre>
                    </div>
                </div>
            </div>

        <?php }else{ ?>

            <div class="col-sm-12">
                <div class="panel panel-green">
                    <div class="panel-heading">
                        <?php echo $value['name'];?>
                    </div>
                </div>
            </div>    
    
        <?php } ?>
    <?php } ?>

    <div class="snep-body-footer-buttons">
        <button type="button" class="btn btn-add btn-primary" onclick="location.reload(true)"><?php echo $this->translate("Test again"); ?></button>
    
    </div>

    <br>


</div>