<div class="row">
    <div class="tab-content">
        <div class="tab-pane active" id="demo">
            <div class="snep-body-top-buttons">
                <div class="snep-body-search">
                    <?php  if($this->key)
                        echo "" ;
                    { ?>
                        <a class='sn-dash-add' style="margin-right: 15px;" href="<?php echo $this->baseUrl ?>/default/index/index?dashboard_add=<?php echo $this->key ?>" title="<?php echo $this->translate('Add to dashboard');?>">
                        </a>   
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
    <?php
    foreach( $this->inspect as $key => $value ) {
        if ($value['error']) { ?>

            <div class="col-sm-12">
                <div class="panel panel-red">
                    <div class="panel-heading">
                        <?php echo $value['name'];?>
                    </div>
                    <div class="panel-body">
                        <pre><?php echo $value['message'];?></pre>
                    </div>
                </div>
            </div>

        <?php }else{ ?>

            <div class="col-sm-12">
                <div class="panel panel-green">
                    <div class="panel-heading">
                        <?php echo $value['name'];?>
                    </div>
                </div>
            </div>    
    
        <?php } ?>
    <?php } ?>

    <div class="snep-body-footer-buttons">
        <button type="button" class="btn btn-add" onclick="location.reload(true)"><?php echo $this->translate("Test again"); ?></button>
    
    </div>

    <br>


</div>