<?php
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/main.css");
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/add.css");
$this->headScript()->appendFile($this->baseUrl() . '/includes/javascript/functions_smarty.js');
$this->headScript()->appendFile($this->baseUrl() . '/includes/javascript/scriptaculous/lib/prototype.js');
$this->headScript()->appendFile($this->baseUrl() . "/includes/javascript/scriptaculous/src/scriptaculous.js", 'text/javascript');
$this->headScript()->appendFile($this->baseUrl() . '/includes/lightbox.js', 'text/javascript');
?>

<div class="snep_form workaround ">
    <?php if ($this->message) : ?>
        <div class="error_box"> <?php echo $this->message ?> </div>
    <?php endif ?>


    <form name="formulario"  method="POST" action="<?php echo $this->url . "/add/" ?>" >

        <table cellspacing="0" align="center">
            <div id="lightboxbody">
                <a id="lightboxLink" href="javascript:void(0);"><img src="/snep/imagens/help.png" class="right"></a>
            </div>

            <div id="containerDiv">
                <h2><?php echo $this->translate("Tarifas - Incluir"); ?></h2>

                <?php echo $this->translate("Esta rotina permite que uma Tarifa seja Cadastrada no Sistema."); ?>

                <br><strong><?php echo $this->translate("Operadora:") ?></strong>
                <?php echo $this->translate("Define o nome da Operadora.") ?>

                <br><strong><?php echo $this->translate("Pais:"); ?></strong>
                <?php echo $this->translate("Define o nome do país."); ?>

                <br><strong><?php echo $this->translate("Estado:"); ?></strong> 
                <?php echo $this->translate("Define a Sigla do Estado."); ?>

                <br><strong><?php echo $this->translate("Cidade:"); ?></strong>
                <?php echo $this->translate("Define o nome do cidade , baseado no estado escolhido."); ?>

                <br><strong><?php echo $this->translate("Código do País:"); ?></strong> 
                <?php echo $this->translate("Define o código DDI do país informado."); ?>

                <br><strong><?php echo $this->translate("Código da Cidade:"); ?></strong> 
                <?php echo $this->translate("Define o código DDD da cidade escolhida."); ?>

                <br><strong><?php echo $this->translate("Prefixo:"); ?></strong>
                <?php echo $this->translate("Define o prefixo de telefones , da cidade 
                    escolhida sobre o qual incidirá a tarifa a ser informada. Caso a tarifa 
                    seja a mesma para todos os prefixos, informe o valor 0000 neste campo."); ?>

                <br><strong><?php echo $this->translate("Tarifa para Fixo:"); ?></strong> 
                <?php echo $this->translate("Define o valor da Tarifa padrão para chamadas a telefones Fixos."); ?>

                <br><strong><?php echo $this->translate("Tarifa para Celular:"); ?></strong> 
                <?php echo $this->translate("Define o valor da Tarifa padrão para chamadas a telefones Celulares."); ?>

                <br><br><strong><?php echo $this->translate("Regras Gerais"); ?></strong>
                <br>
                <?php echo $this->translate("Os valores padrão (Fixo e Móvel) para casa operadora é informado em seu cadastro.
                Para ajustar os valores padrão, deixe os campos com os seguintes dados:"); ?>

                <br><strong><?php echo $this->translate("Estado:"); ?></strong> 
                <?php echo $this->translate("---"); ?>

                <br><strong><?php echo $this->translate("Cidade:"); ?></strong>
                <?php echo $this->translate("Selecione"); ?>

                <br><strong><?php echo $this->translate("Codigo da Cidade:"); ?></strong>
                <?php echo $this->translate("0"); ?>

                <br><strong><?php echo $this->translate("Prefixo:"); ?></strong>
                <?php echo $this->translate("0000"); ?>
                <br>
                <?php echo $this->translate("O cadastro de tarifação deve seguir estas 3 regras:"); ?>

                <br><?php echo $this->translate("1 - Se cidades diferentes tem diferentes valores, 
                    independentemente do PREFIXO do destino, uma Tarifa deve ser criada, informando 
                    o DDD e o PREFIXO correto da cidade.'0000'"); ?>
                <br><?php echo $this->translate("2 - se a operadora tem um valor diferente para alguns 
                    PREFIXOS de uma mesma CIDADE."); ?>
                <br><?php echo $this->translate("3 - Para Tarifação INTERNACIONAL, uma tarifa individual 
                    deve ser criada para cada PAÍS, prestando atenção aos seguintes detalhes:"); ?>
                <br><strong>a)</strong> <?php echo $this->translate("Informe o Código"); ?>
                <br><strong>b)</strong> <?php echo $this->translate("Informe o DDD = 000"); ?>
                <br><strong>c)</strong> <?php echo $this->translate("Informe o PREFIXO = 0000"); ?>
                <br>
                <br>
                <a id="closeLink" href="javascript:void(0);"><?php echo $this->translate("Back"); ?></a><br><br>
            </div> 
            <tr>
                <td valign="top">          
                    <table class="subtable" style="width: 360px;">
                        <tr>
                            <td class="formlabel" width="140px" style="vertical-align:top;">
                                <label class="required"> <?php echo $this->translate("Carrier") ?> :</label>
                            </td>
                            <td class="subtable" >

                                <input type="hidden" name="data" id="data" value="<?php echo Zend_Date::now() ?>" />

                                <select name="operadora" id="operadora" style="width:220px;">
                                    <?php if ($this->carriers): ?>
                                        <?php foreach ($this->carriers as $idCarrier => $carrier) : ?>
                                            <?php if (isset($this->dados['operadora'])) : ?>
                                                <?php if ($idCarrier == $this->dados['operadora']) : ?>
                                                    <option selected=selected value="<?php echo $idCarrier ?>"> <?php echo $carrier ?>
                                                    <?php else : ?>
                                                    <option value="<?php echo $idCarrier ?>"> <?php echo $carrier ?>
                                                    <?php endif ?>
                                                <?php else : ?>
                                                <option value="<?php echo $idCarrier ?>">  <?php echo $carrier ?>
                                                <?php endif ?>
                                            <?php endforeach ?>
                                        <?php endif ?>
                                </select>
                                <?php if (isset($this->error['operadora'])) : ?>
                                    <ul class="errors">
                                        <li>
                                            <?php echo $this->error['operadora']; ?>
                                        </li>
                                    </ul>
                                <?php endif ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="formlabel"  style="vertical-align:top;">
                                <label class="required"> <?php echo $this->translate("Country") ?>:</label>
                            </td>
                            <td class="subtable" >
                                <select id="pais" name="pais"  style="width:220px;">
                                    <option value="BRASIL">BRASIL
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td class="formlabel"  style="vertical-align:top;">
                                <label class="required">  <?php echo $this->translate("State") ?>:</label>
                            </td>
                            <td class="subtable" >
                                <select onchange="cidades(this.value)" name="estado" id="estado"  style="width:220px;">
                                    <?php if ($this->states): ?>
                                        <?php foreach ($this->states as $idState => $state) : ?>
                                            <?php if (isset($this->dados['estado'])) : ?>
                                                <?php if ($idState == $this->dados['estado']) : ?>
                                                    <option selected=selected value="<?php echo $idState ?>"> <?php echo $state ?>
                                                    <?php else : ?>
                                                    <option value="<?php echo $idState ?>"> <?php echo $state ?>
                                                    <?php endif ?>
                                                <?php else : ?>
                                                <option value="<?php echo $idState ?>"> <?php echo $state ?>
                                                <?php endif ?>
                                            <?php endforeach ?>
                                        <?php endif ?>
                                </select>             
                                <div class="waiting" id="wait_estado" style="display:none;">

                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="formlabel"  style="vertical-align:top;">
                                <label class="required">  <?php echo $this->translate("City") ?>:</label>
                            </td>
                            <td class="subtable" >
                                <select name="cidade" id="cidade"  style="width:220px;" >
                                    <?php if ($this->cities): ?>
                                        <?php foreach ($this->cities as $idCity => $city) : ?>
                                            <?php echo "<option value=\"$idCity\">" . $city; ?>
                                        <?php endforeach ?>
                                    <?php endif ?>
                                </select>
                            </td>
                        </tr>

                        <tr>
                            <td class="formlabel"  style="vertical-align:top;">
                                <label class="required">  <?php echo $this->translate("Country Code") ?>:</label>
                            </td>
                            <td class="subtable"  style="vertical-align:top;" >
                                <input name="ddi" id="ddi" type="text" size="5" maxlength="4" value="55" />
                            </td>
                        </tr>

                        <tr>
                            <td class="formlabel"  style="vertical-align:top;">
                                <label class="required">  <?php echo $this->translate("City Code") ?>:</label>
                            </td>
                            <td class="subtable" >
                                <input name="ddd" id="ddd" type="text" value="<?php echo ( isset($this->dados['ddd']) ? $this->dados['ddd'] : "" ) ?>" size="5" maxlength="2" />
                                <?php if (isset($this->error['ddd'])) : ?>
                                    <ul class="errors">
                                        <li>
                                            <?php echo $this->error['ddd']; ?>
                                        </li>
                                    </ul>
                                <?php endif ?>
                            </td>
                        </tr>

                        <tr>
                            <td class="formlabel"  style="vertical-align:top;">
                                <label class="required">  <?php echo $this->translate("Prefix") ?>:</label>
                            </td>
                            <td class="subtable" >
                                <input name="prefixo" id="prefixo" type="text" value="<?php echo ( isset($this->dados['prefixo']) ? $this->dados['prefixo'] : "" ) ?>" size="5" maxlength="4" />
                                <?php if (isset($this->error['prefixo'])) : ?>
                                    <ul class="errors">
                                        <li>
                                            <?php echo $this->error['prefixo']; ?>
                                        </li>
                                    </ul>
                                <?php endif ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="formlabel"> <?php echo $this->translate("Minute Fee for Residencial") ?>:</td>
                            <td class="subtable" >
                                <input name="vfix" id="vfix" class="campos" type="text" value="<?php echo ( isset($this->dados['vfix']) ? $this->dados['vfix'] : "" ) ?>" size="5"  value="0"  style="text-align: right;" />
                                <small> <?php echo $this->translate("Use dot for decimal"); ?> </small>
                            </td>
                        </tr>
                        <tr>
                            <td class="formlabel"> <?php echo $this->translate("Minute Fee for Mobile") ?>:</td>
                            <td class="subtable" >
                                <input name="vcel" id="vcel" class="campos" value="<?php echo ( isset($this->dados['vcel']) ? $this->dados['vcel'] : "" ) ?>" type="text" size="5"  value="0" style="text-align: right;" />
                                <small> <?php echo $this->translate("Use dot for decimal"); ?> </small>
                            </td>
                        </tr>

                    </table>
                </td>
            </tr>
        </table>

        <div class="menus">
            <div style="margin:0 auto; width: 200px;padding: 10px;">
                <input class="submit" type="submit" id="submit" value="<?php echo $this->translate("Save"); ?>">
                <a class="snep_form_cancel" href="<?php echo $this->url ?>"> <?php echo $this->translate('Cancel'); ?> </a>
            </div>
        </div>

    </form>
</div>

<script language="javascript" type="text/javascript">

                                    document.forms[0].elements[0].focus();

                                    function cidades(uf) {

                                        $('wait_estado').show();

                                        var url = '<?php echo $this->url ?>/cidade/';
                                        var params = 'uf=' + uf;
                                        var retorno = new Ajax.Request(
                                                url, {
                                            method: 'POST',
                                            parameters: params,
                                            onComplete: ret_cidade
                                        }
                                        );

                                    }

                                    function ret_cidade(ret) {
                                        $('cidade').innerHTML = "";
                                        $('cidade').insert(ret.responseText);
                                        $('wait_estado').hide();
                                    }

<?php
if (isset($this->dados['estado'])) {
    echo "cidades('{$this->dados['estado']}');";
}
?>


                                    var test;

                                    Event.observe(window, 'load', function() {
                                        test = new Lightbox('containerDiv');
                                    });
                                    Event.observe('lightboxLink', 'click', function() {
                                        test.open();
                                    });
                                    Event.observe('closeLink', 'click', function() {
                                        test.close();
                                    });
</script>


