<div class= "row">
  <div class="tab-content">
    <div class="tab-pane active" id="demo">
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="snep-body-top-buttons">
            <a class="btn btn-add" href="<?php echo $this->url ?>/add/ " role="button" data-intro="<?php echo $this->translate('
            You can <i>Add Tags</i>
            to mark each call with it, than you can view a report with the calls tagged.<br>
            The Tags are organized in a three level tree of codes.');
            ?>"><?php echo $this->translate("Add Tag")?></a>

            <div class="snep-body-search">
              <?php if($this->key){ ?>
                <a class="btn sn-dash-add" href="<?php echo $this->baseUrl ?>/default/index/index?dashboard_add=<?php echo $this->key ?>"  title="<?php echo $this->translate('Add to dashboard');?>"></a>
              <?php } ?>
            </div>
          </div>
        </div><br>

        <table class="table table-striped" id="listtable">
          <thead>
            <tr>
              <th class="text-center"><?php echo $this->translate('Code');?></th>
              <th class="text-center"><?php echo $this->translate('Name');?></th>
              <th class="text-center"><?php echo $this->translate('Type');?></th>
              <th><?php echo $this->translate('Description');?></th>
              <th class="text-center"><?php echo $this->translate('Actions');?></th>
            </tr>
          </thead>
          <tbody class="table-data">
            <?php if( $this->costcenter ) :
              foreach($this->costcenter as $id => $costcenter ): ?>
                <tr>
                  <td class="text-center"> <b> <?php echo $costcenter['codigo'] ?> </b> </td>
                  <td class="text-center"><?php echo $costcenter['nome'] ?> </td>
                  <td class="text-center"><span class="label <?php echo $this->spanTypes[$costcenter['tipo']]?>"><?php echo $this->types[$costcenter['tipo']] ?></span></td>
                  <td><?php echo $costcenter['descricao'] ?> </td>
                  <td align="center">
                    <a class="btn btn-edit btn-sm" href="<?php echo $this->url ?>/edit/id/<?php echo $costcenter['codigo'] ?>" role="button"><?php echo $this->translate('Edit')?></a>
                    <a class="btn btn-danger btn-sm" href="<?php echo $this->url ?>/remove/id/<?php echo $costcenter['codigo'] ?>" role="button"><?php echo $this->translate('Delete')?></a>
                  </td>
                </tr>
              <?php endforeach ?>
            <?php endif?>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

jQuery.noConflict();

jQuery(document).ready(function() {
  jQuery('#listtable').dataTable( {
    "pageLength": <?php echo $this->lineNumber ?>,
    "oLanguage": {
      "sUrl": "/snep/includes/javascript/datatables/media/language/pt-BR.json"
    },
    "bLengthChange": false,
  });
});
</script>
