<form  action="<?php echo $this->url(array("controller" => "auth", "action" => "login"), null, true); ?>" METHOD="post">
    <?php if ($this->message): ?>
        <span class="<?php echo $this->msgclass; ?>"><?php echo $this->message; ?></span>
    <?php endif; ?>
    <dl id="login_form">

        <div class="form_element">
            <dt><?php echo $this->translate("User"); ?>:</dt>
            <dd><input type="text" size="30" id="exten" name="user"></dd>
        </div>

        <div class="form_element">
            <dt><?php echo $this->translate("Password"); ?>:</dt>
            <dd><input type="password" size="30" name="password" /></dd>
        </div>

        <div class="form_element">
            <dt></dt>
            <dd><input type="submit" value="<?php echo $this->translate("Enter"); ?>" /></dd>
        </div>
        <?php $password_recovery = $this->translate("Forgot Password?"); ?>
        <div class="login_password">
            <?php echo "<a href=\"{$this->PAGE}\">$password_recovery<a/>"; ?>
        </div>

    </dl>
</form>

