<link href="/snep/css/login.css" rel="stylesheet">
<link href="/snep/css/bootstrap.css" rel="stylesheet">
<div class="row">
    <?php if($this->message): ?>
        <span class="<?php echo $this->msgclass; ?>"><?php echo $this->message; ?></span>
    <?php endif; ?>

    <form  action="<?php echo $this->url(array("controller" => "auth", "action" => "recuperation"), null, true); ?>" METHOD="post">
        <div id="login">
            <dl id="login_form">
                <div class="login_box">

                    <div class="form-group">
                        <dt><?php echo $this->translate("Username"); ?>:</dt>
                        <input class="form-control" name="username" type="text" autofocus>
                    </div>

                    <div class="form-group">
                        <dt><?php echo $this->translate("New Password"); ?>:</dt>
                        <input class="form-control" name="password" type="password">
                    </div>

                    <div class="form-group">
                        <dt><?php echo $this->translate("Repeat New Password"); ?>:</dt>
                        <input class="form-control" name="newpassword" type="password">
                    </div>

                    <div class="form-group">
                        <dt><?php echo $this->translate("Code sent to your email"); ?>:</dt>
                        <input class="form-control" name="code" type="text">
                    </div>

                    <br />

                    <input type="submit" class="btn btn-lg btn-primary btn-block snep-login" value="<?php echo $this->translate("Save"); ?>" />
                    
                </div>
            </dl>
        </div>
    </form>
</div>
