<?php
//$this->headScript()->appendFile( $this->baseUrl() .'/includes/javascript/scriptaculous/src/scriptaculous.js');
$this->headLink()->appendStylesheet( $this->baseUrl() . "/css/footable/footable.core.css" );
$this->headLink()->appendStylesheet( $this->baseUrl() . "/css/footable/footable-demos.css" );
$this->headLink()->appendStylesheet( $this->baseUrl() . "/css/footable/bootstrap-glyphicons.css" );

?>
<script src="/snep/includes/javascript/footable/footable.js" type="text/javascript"></script>
<script src="/snep/includes/javascript/footable/footable.sort.js" type="text/javascript"></script>
<script src="/snep/includes/javascript/footable/footable.filter.js" type="text/javascript"></script>
<script src="/snep/includes/javascript/footable/footable.paginate.js" type="text/javascript"></script>
<script src="/snep/includes/javascript/footable/bootstrap-tab.js" type="text/javascript"></script>


<style type="text/css">
    .regra0{
        width: 100%;
        height: 30px;
        display: block;
        margin: 0px;
        background-image: url(<?php echo $this->baseUrl();?>/imagens/off.png)  ;
        background-repeat: no-repeat;
        background-position: center;
    }
    .regra1{
        width: 100%;
        height: 30px;
        display: block;
        margin: 0px;
        background-image: url(<?php echo $this->baseUrl() ?>/imagens/on.png);
      background-repeat: no-repeat;
        background-position: center;
    }
</style>

<div id="row">
    
    <div class="tab-content">
        <div class="tab-pane active" id="demo">
            
         <div class="snep-body-top-buttons">
            <a class="btn btn-outline btn-add" href="<?php echo $this->baseUrl ?>/simulator " role="button"><?php echo $this->translate("Simulator")?></a>
            <a class="btn btn-add" href="<?php echo $this->url ?>/add/ " role="button"><?php echo $this->translate("Add Rule")?></a>

            <div class="snep-body-search">
                <?php if($this->key){ ?>
                    <a class="btn btn-adddashboard" type="submit" href="<?php echo $this->baseUrl ?>/default/index/index?dashboard_add=<?php echo $this->key ?>" role="button"></a> <?php echo $this->translate("Dashboard")?>  &nbsp;|&nbsp;  
                <?php } ?>
                <?php echo $this->translate("Search")?> <input id="filter" type="text"/>
            </div>
        </div>
                    
        <?php if ($this->error_message) {
            echo $this->action( 'sneperror', 'error', null, array( 'error_type' => 'alert', 
            'error_title' => $this->translate('Alert'), 'error_message' => $this->error_message, 'error_buttons' => False) );
        } else { ?>
            <table class="table demo table-bordered" data-filter="#filter" data-page-size="<?php echo $this->lineNumber?>">
                <thead>
                    <tr>
                        <th style="width: 10%;" class="text-center" data-type="numeric" ><?php echo $this->translate('Code');?></th>
                        <th style="width: 8%;" class="text-center"><?php echo $this->translate('Active');?></th>
                        <th><?php echo $this->translate('Source');?></th>
                        <th><?php echo $this->translate('Destiny');?></th>
                        <th><?php echo $this->translate('Description');?></th>
                        <th style="width: 12%;" class="text-center" data-type="numeric" data-sort-initial="false"><?php echo $this->translate('Priority');?></th>
                        <th colspan="3" class="text-center" style="width: 20%;" data-sort-ignore="true"><?php echo $this->translate('Actions');?></th>
                    </tr>
                </thead>
                <tbody>

                    <?php foreach($this->routes as $route ): ?>
                        
                        <tr>
                            <td class="text-center"> <b> <?php echo $route['id'] ?> </b> </td>
                            <td class="text-center"> 
                                <span style="cursor:pointer;" alt="<?php echo $this->translate("Enable/Disable"); ?>" id="id<?php echo $route['id']; ?>" class="regra<?php echo $route['ativa']; ?>" onclick="regras(<?php echo $route['id']; ?>)">
                                </span> 
                            </td>
                            <td> <?php echo $route['origem'] ?> </td>
                            <td> <?php echo $route['destino'] ?> </td>
                            <td> <?php echo $route['desc'] ?> </td>
                            <td class="text-center"> <?php echo $route['prio'] ?> </td>
                            <td align="center">
                                <a class="btn btn-default btn-xs"  href='<?php echo $this->baseUrl(); ?>/index.php/route/duplicate/<?php echo $route['id']?>' >
                                    <?php echo $this->translate('Duplicate')?>
                                </a>
                            </td>
                            <td align="center">
                                <a class="btn btn-edit btn-xs"  href='<?php echo $this->baseUrl(); ?>/index.php/route/edit/<?php echo $route['id'] ?>'>
                                    <?php echo $this->translate('Edit')?>
                                </a>
                            </td>
                            <td align="center">
                                <a class="btn btn-danger btn-xs"  href="<?php echo $this->baseUrl ?>/route/remove/id/<?php echo $route['id'] ?>" role="button"><?php echo $this->translate('Delete')?>
                                </a>
                            </td>
                        </tr>
                    <?php endforeach ?>

                </tbody>
                <tfoot>
                    <tr>

                        <td colspan="10">
                            <div class="paging">
                                <ul class="pagination"></ul>
                            </div>
                        </td>
                    </tr>
                </tfoot>
            </table>
        <?php } ?>
    </div> <!-- tab-content -->
</div> <!-- /.row -->


<script type="text/javascript">
    jQuery.noConflict();
    jQuery(function () {
        jQuery('table').footable().on('click', '.row', function(e) {
            e.preventDefault(); 
        });
    });

    function regras(par) {
        if(jQuery('#id' + par).attr('class')=='regra0') {
            troca_status(par);
            jQuery('#id' + par).attr('class', 'regra1');
        } else {
            troca_status(par);
            jQuery('#id' + par).attr('class', 'regra0');
        }
    }

    function troca_status(id) {

        jQuery.post('<?php echo $this->baseUrl(); ?>/index.php/route/toogle/', {route: id});
        
    }

</script>


