<?php
/**
 *  This file is part of SNEP.
 *
 *  SNEP is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  SNEP is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with SNEP.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Index View for class NewRotues
 *
 * @category  Snep
 * @package   Snep
 * @copyright Copyright (c) 2015 OpenS Tecnologia
 * @author    Opens Tecnologia <desenvolvimento@opens.com.br>
 */

$this->headLink()->appendStylesheet( $this->baseUrl() . "/css/route.css" );
?>

<div class= "row">
  <div class="tab-content">
    <div class="tab-pane active" id="demo">
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="snep-body-top-buttons">
            <a class="btn btn-outline btn-add" style="margin-right: 5px;" href="<?php echo $this->baseUrl ?>/simulator " role="button" data-intro="<?php echo $this->translate('You can Simulate what will happen when a call are made!');?>"><?php echo $this->translate("Simulator")?></a>
            <a class="btn btn-add" href="<?php echo $this->url ?>/add/ " role="button"><?php echo $this->translate("Add Rule")?></a>
            <div class="btn-group">
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <?php echo $this->translate("Filter by")?> <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" >
                <li><a class="btn-default" href="<?php echo $this->baseUrl(); ?>/index.php/route?type=incoming"><?php echo $this->translate("Incoming Rule Only")?></a></li>
                <li><a class="btn-default" href="<?php echo $this->baseUrl(); ?>/index.php/route?type=outgoing"><?php echo $this->translate("Outgoing Rule Only")?></a></li>
                <li><a class="btn-default" href="<?php echo $this->baseUrl(); ?>/index.php/route?type=others"><?php echo $this->translate("Others Rule Only")?></a></li>
                <li role="separator" class="divider"></li>
                <li><a class="btn-default" href="<?php echo $this->baseUrl(); ?>/index.php/route"><?php echo $this->translate("All rules")?></a></li>
              </ul>
            </div>
            <?php if ($this->hide_routes === "1") {?>
              <span class=" btn hide_rules_enable">
                <span class="sn-visivel fa-fw" style="font-size: 14px;"></span>
                <?php echo $this->translate("Hide routes is enable")?>
              </span>
            <?php } ?>

            <div class="snep-body-search" >
              <?php if($this->key){ ?>
                <a class='sn-dash-add' href="<?php echo $this->baseUrl ?>/default/index/index?dashboard_add=<?php echo $this->key ?>" title="<?php echo $this->translate('Add to dashboard');?>" data-intro="<?php echo $this->translate('You can Add a shortcut of this screen to your Dashboard')?>"></a>
              <?php } ?>
            </div>
          </div>
        </div><br>

        <?php if ($this->error_message) {
          echo $this->action( 'sneperror', 'error', null, array( 'error_type' => 'alert','error_title' => $this->translate('Alert'), 'error_message' => $this->error_message, 'error_buttons' => False) );
        } else { ?>

          <table class="table table-striped" id="listtable">
            <thead>
              <tr>
                <th class="text-center"><?php echo $this->translate('Id');?></th>
                <th class="text-center"><?php echo $this->translate('Prio');?></th>
                <th class="text-center"><?php echo $this->translate('Source');?></th>
                <th class="text-center"><?php echo $this->translate('Destiny');?></th>
                <th><?php echo $this->translate('Description');?></th>
                <th class="text-center"><?php echo $this->translate('Record');?></th>
                <th class="text-center" data-intro="<?php echo $this->translate('You can Activate or Deactive Routes')?>"><?php echo $this->translate('Actions');?></th>
              </tr>
            </thead>
            <tbody>
              <?php foreach($this->routes as $route ): ?>
                <tr>
                  <td class="text-center"> <?php echo $route['id'] ?>  </td>
                  <td class="text-center"> <?php echo $route['prio'] ?> </td>
                  <td class="text-center"> <?php echo $route['origem'] ?> </td>
                  <td class="text-center"> <?php echo $route['destino'] ?> </td>
                  <td> <?php echo $route['desc'] ?> </td>
                  <td class="text-center"> 
                    <?php if(intval($route['record'])){ ?> 
                      <label class="label label-success"><?php echo $this->translate("Yes") ?></label>
                    <?php }else{ ?> 
                      <label class="label label-danger"><?php echo $this->translate("No") ?></label>
                    <?php } ?> 
                  </td>
                  <td class="text-center">
                    <div class="checkbox">
                      <label><input type="checkbox" data-toggle="toggle" data-size="small" <?php echo $route['ativa'] === '1' ? 'checked' : ''; ?> id="rule_state" value="<?php echo $route['id'];?>" onchange="change_status(this.value)" ></label>
                    </div>
                    <a class="btn btn-default btn-sm"  href='<?php echo $this->baseUrl(); ?>/index.php/route/duplicate/<?php echo $route['id']?>' ><?php echo $this->translate('Duplicate')?></a>
                    <a class="btn btn-edit btn-sm"  href='<?php echo $this->baseUrl(); ?>/index.php/route/edit/<?php echo $route['id'] ?>'><?php echo $this->translate('Edit')?></a>
                    <a class="btn btn-danger btn-sm"  href="<?php echo $this->baseUrl ?>/route/remove/id/<?php echo $route['id'] ?>" role="button"><?php echo $this->translate('Delete')?></a>
                  </td>
                </tr>
              <?php endforeach ?>
            </tbody>
          </table>
        <?php } ?>
      </div>
    </div> 
</div> 


<script type="text/javascript">
jQuery.noConflict();

jQuery(document).ready(function() {
  jQuery('#listtable').dataTable( {
    "pageLength": <?php echo $this->lineNumber ?>,
    "order": [[ 1, "desc" ]],
    "oLanguage": {
      "sUrl": "/snep/includes/javascript/datatables/media/language/pt-BR.json"
    },
    "bLengthChange": false,
  });
});

/*
 * Change rule status
 * @param id - rule id
 */
function change_status(id) {
    jQuery.post('<?php echo $this->baseUrl(); ?>/index.php/route/toogle/', {route: id});
}
</script>
