
<form  action="<?php echo $this->url(array("controller" => "auth", "action" => "redefine"), null, true); ?>" METHOD="post">
    <?php if ($this->message): ?>
        <span class="<?php echo $this->msgclass; ?>"><?php echo $this->message; ?></span>
    <?php endif; ?>
    <dl id="login_form">

        <div class="form_element">
            <span class="<?php echo $this->msgclass; ?>"><?php echo $this->translate("Enter your user to send a redefinition of the password to your registered email "); ?></span>
        </div>

        <div class="form_element">
            <dt><?php echo $this->translate("User"); ?>:</dt>
            <dd><input type="text" size="30" id="exten" name="user"></dd>
        </div>

        <div class="form_element">
            <dt></dt>
            <dd><input type="submit" value="<?php echo $this->translate("Send"); ?>" /></dd>
        </div>

    </dl>
</form>