<input type="hidden" name="phoneValue" id="phoneValue" value="--"  /><?php echo $this->translate("DDD + Number. Example: 4899999999"); ?>
<ul id="phone" style="list-style:none; padding: 0px; margin: 0px;"  onkeypress="return onlyDigit(event)" ></ul>


<script type="text/javascript">
    function onlyDigit(e) {
        var unicode = e.charCode ? e.charCode : e.keyCode;
        if (unicode != 8 && unicode != 9) {
            if (unicode < 48 || unicode > 57) {
                return false
            }
        }
    }
</script>