<div class= "row">
  <div class="tab-content">
    <div class="tab-pane active" id="demo">
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="snep-body-top-buttons">
            <a class="btn btn-add" href="<?php echo $this->url ?>/add/ " role="button"><?php echo $this->translate("Add Extension")?></a>
            <a class="btn btn-outline btn-add" href="<?php echo $this->url ?>/multiadd/ " role="button"><?php echo $this->translate("Add Multiple")?></a>
            <?php if(class_exists("Invite_Signup")){ ?>
              <a class="btn btn-outline btn-add" href="<?php echo $this->baseUrl ?>/invite/invite/add" role="button"><?php echo $this->translate("Send Invite")?></a>
            <?php } ?>
            <a class="btn btn-outline btn-add" href="<?php echo $this->url ?>/multiremove/ " role="button"><?php echo $this->translate("Remove Multiple")?></a>
            <div class="snep-body-search">
              <?php if($this->key){ ?>
                <a class='sn-dash-add' href="<?php echo $this->baseUrl ?>/default/index/index?dashboard_add=<?php echo $this->key ?>" title="<?php echo $this->translate('Add to dashboard');?>"></a>
              <?php } ?>
            </div>
          </div>
        </div><br>
        
        <?php if ($this->alert_message) { ?>
          <div class="alert alert-danger"><?php echo $this->alert_message; ?></div>
        <?php }  ?>
          <table class="table table-striped" id="listtable">
            <thead>
              <tr>
                <th class="text-center"><?php echo $this->translate('Extension');?></th>
                <th class="text-center"><?php echo $this->translate('Caller ID');?></th>
                <th class="text-center"><?php echo $this->translate('Channel');?></th>
                <th class="text-center"><?php echo $this->translate('Extension Group');?></th>
                <th class="text-center"><?php echo $this->translate('Actions');?></th>
              </tr>
            </thead>  
            <tbody>
              <?php foreach($this->extensions as $cha => $val ): ?>
                <tr>
                  <td class="text-center"> <b> <?php echo $val['exten'] ?> </b> </td>
                  <td class="text-center"> <?php
                    $nameValue = explode("<", $val['name']);
                    $callerid = $nameValue[0];
                    echo $callerid ?> 
                  </td>
                  <td class="text-center"> <?php echo $val['channel'] ?> </td>
                  <td class="text-center"> <?php echo $val['groups'] ?> </td>
                  <td class="text-center">
                    <a class="btn btn-edit btn-sm" href='<?php echo $this->url ?>/edit/id/<?php echo $val['exten'] ?>' role="button"><?php echo $this->translate('Edit')?></a>
                    <a class="btn btn-danger btn-sm"  href='<?php echo $this->url ?>/remove/id/<?php echo $val['exten'] ?>'><?php echo $this->translate('Delete')?></a>
                    <?php if ($val['disabled'] == false) { ?>
                      <a class="btn btn-info btn-sm"  href='<?php echo $this->url ?>/disable/id/<?php echo $val['exten'] ?>'><?php echo $this->translate('Disable')?></a>
                    <?php }else{ ?>
                      <a class="btn btn-primary btn-sm"  href='<?php echo $this->url ?>/enable/id/<?php echo $val['exten'] ?>'><?php echo $this->translate('Enable')?></a>
                    <?php } ?>
                  </td>
                </tr>
              <?php endforeach ?>
            </tbody>
          </table>
        </div>
      </div>
    </div>
</div>

<script type="text/javascript">
jQuery.noConflict();

jQuery(document).ready(function() {
  jQuery('#listtable').dataTable( {
    "pageLength": <?php echo $this->lineNumber ?>,
    "oLanguage": {
      "sUrl": "/snep/includes/javascript/datatables/media/language/pt-BR.json"
    },
    "bLengthChange": false,
  });
});
</script>
