<div class= "row">
  <div class="tab-content">
    <div class="tab-pane active" id="demo">
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="snep-body-top-buttons">
            <a class="btn btn-add" href="<?php echo $this->url ?>/add/ " role="button"><?php echo $this->translate("Add Extension Group")?></a>
            <div class="snep-body-search">
              <?php if($this->key){ ?>
                <a class='sn-dash-add' href="<?php echo $this->baseUrl ?>/default/index/index?dashboard_add=<?php echo $this->key ?>" title="<?php echo $this->translate('Add to dashboard');?>"></a>
              <?php } ?>
            </div>
          </div>
        </div><br>
        
        <table class="table table-striped" id="listtable">
          <thead>
            <tr>
              <th class="text-center"><?php echo $this->translate('Code');?></th>
              <th class="text-center"><?php echo $this->translate('Name');?></th>
              <th class="text-center"><?php echo $this->translate('Peers in');?></th>
              <th class="text-center"><?php echo $this->translate('Actions');?></th>
            </tr>
          </thead>
          <tbody>
            <?php if($this->extensionsgroups):
              foreach($this->extensionsgroups as $group ):
                $disabled = $group['id'] === '1' ? "disabled" : "";  ?>
                <tr>
                  <td class="text-center"><?php echo $group['id'] ?></td>
                  <td class="text-center"><?php echo $group['name'] ?></td>
                  <td class="text-center"><label class="label label-info"><?php echo $group['qt_peers'] ?></label></td>
                  <td class="text-center">
                    <a class="btn btn-edit btn-sm" href="<?php echo $this->url ?>/edit/id/<?php echo $group['id'] ?>" role="button"><?php echo $this->translate('Edit')?></a>
                    <a class="btn btn-danger btn-sm <?php echo $disabled ?>" href="<?php echo $this->url ?>/remove/id/<?php echo $group['id'] ?>" role="button"><?php echo $this->translate('Delete')?></a>
                  </td>
                </tr>
              <?php endforeach ;
            endif ?>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

jQuery.noConflict();

jQuery(document).ready(function() {
  jQuery('#listtable').dataTable( {
    "pageLength": <?php echo $this->lineNumber ?>,
    "oLanguage": {
      "sUrl": "/snep/includes/javascript/datatables/media/language/pt-BR.json"
    },
    "bLengthChange": false,
  });
});
</script>
