<?php
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/system_status.css");
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/bootstrap.min.css");
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/bootstrap-responsive.min.css");
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/font-awesome/css/font-awesome.min.css");
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/style.css");
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/pages/dashboard.css");
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/odometer.css");

?>

<div class="snep_form">
        
    <?php if ($this->error) : ?>
        <div class="error_box" >
            <?php echo $this->translate("Errors were detected in the configuration of SNEP, click "); ?>
            <a href="<?php echo $this->inspector; ?>">
                <?php echo $this->translate("here"); ?>
            </a>
            <?php echo $this->translate(" for more information"); ?>
        </div>
    <?php endif ?>

    <?php if ($this->erroast) : ?>
        <div class="error_box" >
            <?php echo $this->translate("Failed to connect to server Asterisk"); ?>

        </div>
    <?php endif ?>

    <div class="subnavbar">
        <div class="subnavbar-inner">

         <a class="btn btn-navbar btn-info visible-phone" data-toggle="collapse" data-target=".nav-collapse">
            
            <span class="icon-bar"></span>
          </a>

            <div class="container nav-collapse">

                <ul>
                    <li>

                        <a class="js-smoothscroll" href="#refresh-os">
                            <img alt="" src="<?php echo $this->baseUrl(); ?>/imagens/index/server_status_icon.png" width="40" height="40">
                            <span><?php echo $this->translate("System"); ?></span>
                        </a>
                    </li>
                    
                    <li>
                        <a class="js-smoothscroll" href="#refresh-df">
                            <img alt="" src="<?php echo $this->baseUrl(); ?>/imagens/index/storage_icon.png" width="36" height="36">
                            <span><?php echo $this->translate("Disk"); ?></span>
                        </a>
                    </li>
                    
                    <li>
                        <a class="js-smoothscroll" href="#refresh-ram">
                            <img alt="" src="<?php echo $this->baseUrl(); ?>/imagens/index/memory_icon.png" width="51" height="40">
                            <span><?php echo $this->translate("Memory"); ?></span>
                        </a>
                    </li>

                    <li>
                        <a class="js-smoothscroll" href="#refresh-ispeed">
                        <img alt="" src="<?php echo $this->baseUrl(); ?>/imagens/index/network.png" width="37" height="40">
                            <span><?php echo $this->translate("Internet"); ?></span>
                        </a>
                    </li>

                    <li>
                        <a class="js-smoothscroll" href="#refresh-ip">
                        <img alt="" src="<?php echo $this->baseUrl(); ?>/imagens/index/ip.png" width="37" height="40">
                            <span><?php echo $this->translate("IP"); ?></span>
                        </a>
                    </li>

                    <li>
                        <a class="js-smoothscroll" href="#refresh-modules">
                        <img alt="" src="<?php echo $this->baseUrl(); ?>/imagens/index/modules_icon.png" width="37" height="40">
                            <span><?php echo $this->translate("Modules"); ?></span>
                        </a>
                    </li>
                    
                    <li>
                        <a class="js-smoothscroll" href="#refresh-ispeed">
                        <img alt="" src="<?php echo $this->baseUrl(); ?>/imagens/index/stats_icon.png" width="37" height="40">
                            <span><?php echo $this->translate("PBX Statistics"); ?></span>
                        </a>
                    </li>
                    
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i id="closed-widget-count">0</i>
                            <span> <?php echo $this->translate('Closed Widgets'); ?> <i class="icon-caret-down"></i></span>
                        </a>
                        
                        <ul class="dropdown-menu" id="closed-widget-list">
                            <li id="close-all-widgets">
                                <a> <i class="icon-remove lead pull-left"></i> <?php echo $this->translate('Close All Widgets'); ?></a>
                            </li>
                            <li id="open-all-widgets">
                                <a> <i class="icon-plus lead pull-left"></i> <?php echo $this->translate('Open All Widgets'); ?></a>
                            </li>
                            <li class=""><hr></li>
                        </ul>
                    </li>
        
                </ul>
            </div>
        </div>
    </div>

    <div class="main">
        <div class="main-inner">
            <div class="container">
                <div id="widgets" class="row">
                    <div class="span4">
                        <div id="general-info-widget" class="widget widget-table action-table">
                            <div class="widget-header" >
                                <img alt="" src="<?php echo $this->baseUrl(); ?>/imagens/index/server_status_icon.png" width="30" height="30">
                                    <h3>
                                        <?php echo $this->translate("System"); ?>
                                    </h3> 
                                    <div id="refresh-os" class="btn icon-refresh js-refresh-info"></div>   
                            </div>
                            
                            <div class="widget-content">
                                <div class="general-info-item">
                                    <span class="general-title"><?php echo $this->translate("Distribution"); ?></span>
                                    <span class="general-data" ><?php echo $this->indexData["linux_ver"]; ?></span>
                                </div>
                                <div class="general-info-item">
                                    <span class="general-title"><?php echo $this->translate("Kernel"); ?></span>
                                    <span class="general-data" ><?php echo $this->indexData['linux_kernel']; ?></span>
                                </div>
                                <div class="general-info-item">
                                    <span class="general-title"><?php echo $this->translate("CPU"); ?></span>
                                    <span class="general-data" ><?php echo $this->indexData["hardware"]; ?></span>
                                </div>
                                <div class="general-info-item">
                                    <span class="general-title"><?php echo $this->translate("Turn-on Time"); ?></span>
                                    <span><?php echo $this->indexData["uptime"]; ?></span>
                                </div>
                                <div class="general-info-item">
                                    <span class="general-title"><?php echo $this->translate("Asterisk"); ?></span>
                                    <span><?php echo $this->indexData["asterisk"]; ?></span>
                                </div>
                                <div class="general-info-item">
                                    <span class="general-title"><?php echo $this->translate("MySQL"); ?></span>
                                    <span><?php echo $this->indexData["mysql"]; ?></span>
                                </div>
                                <div class="general-info-item">
                                    <span class="general-title">Hostname</span>
                                    <span id="os-hostname"></span>
                                </div>
                            </div>
                        </div>
                    </div>  

                    <div class="span5">
                        <div id="disk-usage-widget" class="widget widget-table">
                            <div class="widget-header">
                                <img alt="" src="<?php echo $this->baseUrl(); ?>/imagens/index/storage_icon.png" width="30" height="30">
                                <h3><?php echo $this->translate("Disk"); ?></h3>
                                <div id="refresh-df" class="btn icon-refresh js-refresh-info"></div>
                                
                                <div class="widget-content">
                                <div class="big-stats-container">
                                    <div class="widget-content">
                                        <div class="cf big_stats">
                                            
                                            <div class="stat">
                                                <i class="icon-#"><?php echo $this->translate("Partition"); ?></i> 
                                                <?php foreach ($this->indexData["space"] as $key => $value) { ?>
                                                    <br><span><?php echo $value["mount_point"]; ?></span>
                                                <?php } ?>
                                            </div>

                                            <div class="stat">
                                                <i class="icon-#"><?php echo $this->translate("Total"); ?></i> 
                                                <?php foreach ($this->indexData["space"] as $key => $value) { ?>
                                                    <br><span><?php echo sprintf("%.2f", ($value["size"] / 1048576)); ?></span>
                                                <?php } ?>
                                            </div>

                                            <div class="stat">
                                                <i class="icon-#"><?php echo $this->translate("Livre"); ?></i> 
                                                <?php foreach ($this->indexData["space"] as $key => $value) { ?>
                                                    <br><span><?php echo sprintf("%.2f", ($value["free"] / 1048576)) ?></span>
                                                    <?php echo "(".(100 - $value["percent"])."%)";?>
                                                    
                                                <?php } ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>    

                    <div class="span3">
                        <div id="ram-widget" class="widget widget-nopad">
                            <div class="widget-header">
                                <img alt="" src="<?php echo $this->baseUrl(); ?>/imagens/index/memory_icon.png" width="30" height="30">
                                <h3><?php echo $this->translate("Memory"); ?></h3>
                                <div id="refresh-ram" class="btn icon-refresh js-refresh-info"></div>
                            </div>
                            
                            <div class="widget-content">
                                <div class="big-stats-container">
                                    <div class="widget-content">
                                        <div class="cf big_stats">
                                            <div class="stat">
                                                <i class="icon-#"><?php echo $this->translate("Total"); ?>&nbsp;</i> <span class="value odometer" id="ram-total"></span> MB
                                            </div><!-- .stat -->
                                            <div class="stat">
                                                <i class="icon-#"><?php echo $this->translate("Used"); ?>&nbsp;</i> <span class="value odometer" id="ram-used"></span> MB<br>
                                                <span class="value odometer" id="ram-used-per"></span> %
                                            </div><!-- .stat -->
                                            <div class="stat">
                                                <i class="icon-#"><?php echo $this->translate("Free"); ?>&nbsp;</i> <span class="value odometer" id="ram-free"></span> MB<br>
                                                <span class="value odometer" id="ram-free-per"></span> %
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div> 

                    <div class="span3">
                        <div id="internet-speed-widget" class="widget widget-table">
                            <div class="widget-header">
                            <img alt="" src="<?php echo $this->baseUrl(); ?>/imagens/index/network.png" width="30" height="30">
                                <h3><?php echo $this->translate("Internet Speed"); ?></h3>
                                <div id="refresh-ispeed" class="btn js-refresh-info"><span class="icon-refresh"></span></div>
                            </div>
                            <div class="widget-content">
                                <div style="padding: 0; text-align: center;">
                                    <i class="icon-download" style="font-size:18px;"></i>
                                    <span class="lead value odometer" style="margin-top:11px;" id="ispeed-rate-downstream">0</span>
                                    <span class="lead">Mbps</span>
                                </div>
                                <div style="padding: 0; text-align: center;">
                                    <i class="icon-upload" style="font-size:18px;"></i>
                                    <span class="lead value odometer" style="margin-top:11px;" id="ispeed-rate-upstream">0</span>
                                    <span class="lead">Mbps</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="span3">
                        <div id="ip-widget" class="widget widget-table">
                            <div class="widget-header">
                            <img alt="" src="<?php echo $this->baseUrl(); ?>/imagens/index/ip.png" width="30" height="30">
                                <h3><?php echo $this->translate("IP"); ?></h3>
                                <div id="refresh-ip" class="btn icon-refresh js-refresh-info"></div>
                            </div>
                            <div class="widget-content">
                                <table id="ip_dashboard" class="table table-hover table-condensed table-bordered"></table>
                            </div>
                        </div>
                    </div>

                    <div class="span6">
                        <div id="modules-widget" class="widget widget-table action-table">
                            <div class="widget-header" >
                                <img alt="" src="<?php echo $this->baseUrl(); ?>/imagens/index/modules_icon.png" width="30" height="30">
                                    <h3>
                                        <?php echo $this->translate("Modules"); ?>
                                    </h3> 
                                    <div id="refresh-modules" class="btn icon-refresh js-refresh-info"></div>   
                            </div>

                            <?php    
                            foreach ($this->indexData["modules"] as $key => $value) { ?>
                            
                            <div class="widget-content">
                                <div class="general-info-item">
                                    <span class="general-title"><?php echo $value['name'] . " - " .$value['version'] . " - " .$value['description']; ?></span>
                                </div>
                            </div>
                                
                            
                            <?php } 
                            ?>
                            
                            
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>

    <script src="../includes/javascript/jquery.js" type="text/javascript"></script>
    <script src="../includes/javascript/jquery-ui.min.js" type="text/javascript"></script>
    <script src="../includes/javascript/bootstrap.js" type="text/javascript"></script>
    <script src="../includes/javascript/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="../includes/javascript/odometer.js" type="text/javascript"></script>
    <script src="../includes/javascript/dashboard.js" type="text/javascript"></script>
    <script src="../includes/javascript/base.js" type="text/javascript"></script>

</div>






    

    



