<div class= "row">
  <div class="tab-content">
    <div class="tab-pane active" id="demo">
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="snep-body-top-buttons">
            <a class="btn btn-add" href="<?php echo $this->url ?>/add/ " role="button"><?php echo $this->translate("Add Trunk")?></a>
            <div class="snep-body-search">
              <?php if($this->key){ ?>
                <a class='sn-dash-add' href="<?php echo $this->baseUrl ?>/default/index/index?dashboard_add=<?php echo $this->key ?>" title="<?php echo $this->translate('Add to dashboard');?>"></a>
              <?php } ?>
            </div>
          </div>
        </div><br>
        <table class="table table-striped" id="listtable">
          <thead>
            <tr>
              <th class="text-center"><?php echo $this->translate('Code');?></th>
              <th class="text-center"><?php echo $this->translate('Name');?></th>
              <th class="text-center"><?php echo $this->translate('Type');?></th>
              <th class="text-center"><?php echo $this->translate('Interface Type');?></th>
              <th class="text-center"><?php echo $this->translate('Time Credit (minutes)');?></th>

              <th class="text-center"><?php echo $this->translate('Actions');?></th>
            </tr>
          </thead>
          <tbody>
            <?php foreach($this->trunks as $id => $trunk ): ?>
              <tr>
                <td class="text-center"><?php echo $trunk['name'] ?> </td>
                <td class="text-center"> <?php echo $trunk['callerid'] ?> </td>
                <td class="text-center">
                  <?php echo ( $trunk['trunktype'] == "T" ?  $this->translate("TDM") : $this->translate("IP") )  ?>
                </td>
                <td class="text-center"> <?php echo $trunk['technology'] ?> </td>
                <td class="text-center">
                  <?php if ($trunk['saldo']) : ?>
                    <span style='color:#888'><?php echo $trunk['saldo']  ?> <?php echo $this->translate('minutes') ?></span>
                  <?php else :  ?>
                    <?php echo $this->translate('Not configured') ?>
                  <?php endif ?>
                </td>
                <td class="text-center">
                  <a class="btn btn-edit btn-sm"  href="<?php echo $this->url ."/edit/trunk/".  $trunk['id'] ?>" role="button"><?php echo $this->translate('Edit')?></a>
                  <a class="btn btn-danger btn-sm" href="<?php echo $this->url ."/remove/id/".  $trunk['id'] . "/name/" . $trunk['name'] ?>" role="button"><?php echo $this->translate('Delete')?></a>
                  <?php if($trunk['disabled']){ ?>
                    <a class="btn btn-primary btn-sm" href="<?php echo $this->url ."/enable/id/".  $trunk['id'] . "/name/" . $trunk['name'] ?>" role="button"><?php echo $this->translate('Enable')?></a>
                  <?php } ?>
                </td>
              </tr>
            <?php endforeach ?>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

jQuery.noConflict();

jQuery(document).ready(function() {
  jQuery('#listtable').dataTable( {
    "pageLength": <?php echo $this->lineNumber ?>,
    "oLanguage": {
      "sUrl": "/snep/includes/javascript/datatables/media/language/pt-BR.json"
    },
    "bLengthChange": false,
  });
});
</script>


