<?php
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/index.css");
$this->headScript()->appendFile('/snep/includes/javascript/scriptaculous/src/scriptaculous.js');
$this->headScript()->appendFile('/snep/includes/javascript/registrations.js');
?>

<div>
    <form name="tabela" id="tabela">
        <input type="hidden" value="" id="selected" />
        <table align="center">
            <thead>
                <tr>
                    <td class="cen"><?php echo $this->calldate; ?></td>
                    <td class="esq"><?php echo $this->src; ?></td>
                    <td class="esq"><?php echo $this->dst; ?></td>
                    <td class="esq"><?php echo $this->duration; ?></td>
                    <td class="esq"><?php echo $this->billsec; ?></td>
                    <td class="esq"><?php echo $this->disposition; ?></td>
                    <td class="esq"><?php echo $this->gravation; ?></td>
                </tr>
            </thead>
            <?php $c = 0; ?>
            <?php foreach ($this->dados as $id => $dado): ?>
                <?php ( $c ? $c = 0 : $c = 1 ); ?>
                <tr  class="c<?php echo $c ?>" >

                    <td>
                        <?php echo date("d/m/Y H:i", strtotime($dado['calldate']));?> 
                    </td>
                    <td>
                        <?php echo $dado['src']; ?> 
                    </td>
                    <td>
                        <?php echo $dado['dst']; ?> 
                    </td>
                    <td>
                        <?php echo $dado['disposition']; ?> 
                    </td>
                    <td>
                        <?php echo $dado['duration'] ?>	
                    </td>
                    <td>
                        <?php echo $dado['billsec'] ?>	
                    </td>

                    <td style="text-align:center">
                        <?php if ($dado['userfield'] != ""): ?>
                            <?php if ($dado['file_path'] != 'N.D.'): ?>

                                <input type="checkbox"  value="<? echo $dado['file_path']; ?>">
                                <a href="<?php echo $dado['file_path']; ?>" class="link_esp_1">
                                    <img src="/snep/imagens/ouvir.png" />
                                </a>
                            <?php else: ?>
                                <img src="/snep/imagens/semaudio.png" />
                            <?php endif ?>
                        <?php else: ?>
                            ---
                        <?php endif ?>
                    </td>
                <?php endforeach ?>
            </tr>
        </table>
    </form>

    <?php echo $this->render('pagination.phtml');
    ?>

    <script>
        function compactCheckeds() {
            var form = $('tabela');
            var i = form.getElements('checkbox');
            var dados = '';
            i.each(function(item) {
                if (item.checked) {
                    dados += item.value + ",";
                }
            });

            var url = '/snep/index.php/default/record-report/compact/';
            var params = 'files=' + dados;
            var retorno = new Ajax.Request(
                    url, {
                method: 'get',
                parameters: params,
                onComplete: alerta
            }
            );
        }

        function alerta(arq) {
            var arq = arq.responseText;
            if (arq == 0) {
                alert("Erro");
            } else {
                alert("<?php echo $this->compact_success ?>");
                window.location = arq;
            }
        }

    </script> 

</div>

<div class="form_compress">
    <input type="submit" value="<?php echo $this->compress_files ?>" OnClick="compactCheckeds();">
</div>