<?php
$this->headLink()->appendStylesheet( $this->baseUrl() . "/css/footable/footable.core.css" );
$this->headLink()->appendStylesheet( $this->baseUrl() . "/css/footable/footable-demos.css" );
$this->headLink()->appendStylesheet( $this->baseUrl() . "/css/footable/bootstrap-glyphicons.css" );
$this->headScript()->appendFile($this->baseUrl() .  "/includes/javascript/snep.js");
?>

<script src="/snep/includes/javascript/footable/footable.js" type="text/javascript"></script>
<script src="/snep/includes/javascript/footable/footable.sort.js" type="text/javascript"></script>
<script src="/snep/includes/javascript/footable/footable.filter.js" type="text/javascript"></script>
<script src="/snep/includes/javascript/footable/footable.paginate.js" type="text/javascript"></script>
<script src="/snep/includes/javascript/footable/bootstrap-tab.js" type="text/javascript"></script>

<div class="row">
    
    <div class="tab-content">
        <div class="tab-pane active" id="demo">

            <div class="snep-body-top-buttons">
                <a class="btn btn-add" href="<?php echo $this->url ?>/addfile/class/default " role="button"><?php echo $this->translate("Add File")?></a>
                <div class="snep-body-search">
                    <?php echo $this->translate("Search")?> <input id="filter" type="text"/>
                </div>
            </div>
             <?php if ($this->error_message) {
                echo $this->action( 'sneperror', 'error', null, array( 'error_type' => 'alert', 
            'error_title' => $this->translate('Alert'), 'error_message' => $this->error_message, 'error_buttons' => False) );
            } else { ?>

                <table class="table demo table-bordered" data-filter="#filter" data-page-size="<?php echo $this->lineNumber?>">

                    <thead>
                        <tr>
                            <th> <?php echo $this->translate('Name') ?> </th>
                            <th> <?php echo $this->translate('Date') ?> </th>
                            <th> <?php echo $this->translate('Description') ?> </th>
                            <th> <?php echo $this->translate('Class') ?> </th>
                            <th colspan="4" class="action text-center" data-sort-ignore="true"> <?php echo $this->translate('Actions') ?> </th>
                        </tr>
                    </thead>
                    <tbody>
                        
                        <?php if($this->files):
                            foreach($this->files as $file ): ?>
                                                               
                                <tr>
                                    <td> <b> <?php echo $file['arquivo'] ?> </b> </td>
                                    <td> <?php echo  ( $file['data'] ?  new Zend_Date( $file['data']) : '-' );  ?> </td>
                                    <td><?php echo $file['descricao'] ?> </td>
                                    <td><?php echo $file['secao'] ?> </td>
                                    <td align="center">
                                        <a class="btn btn-edit btn-xs"  href="<?php echo $this->url ?>/editfile/file/<?php echo $file['arquivo']?>/class/<?php echo $file['secao']?>" role="button"><?php echo $this->translate('Edit')?> 
                                        </a>
                                    </td>
                                    <td align="center">
                                        <a class="btn btn-danger btn-xs"  href="<?php echo $this->url ?>/removefile/file/<?php echo $file['arquivo']?>/class/<?php echo $file['secao']?>" role="button"><?php echo $this->translate('Delete')?> 
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach ?>
                        <?php endif ?>
                    </tbody>
                    <tfoot>
                        <tr>

                            <td colspan="7">
                                <div class="paging">
                                    <ul class="pagination"></ul>
                                </div>
                            </td>
                        </tr>
                    </tfoot>
                </table>
                <?php } ?>
            <br>
        </div> <!-- demo -->
    </div> <!-- tab-content -->
</div> <!-- /.row -->


<script type="text/javascript">
    jQuery.noConflict();
    jQuery(function () {
        jQuery('table').footable().on('click', '.row', function(e) {
            e.preventDefault(); 
        });
    });
</script>





