<?php
/**
 *  This file is part of SNEP.
 *
 *  SNEP is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as
 *  published by the Free Software Foundation, either version 3 of
 *  the License, or (at your option) any later version.
 *
 *  SNEP is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with SNEP.  If not, see <http://www.gnu.org/licenses/lgpl.txt>.
 */

$this->headScript()->appendFile($this->baseUrl() .  "/includes/javascript/snep.js");
?>

<div class= "row">
  <div class="tab-content">
    <div class="tab-pane active" id="demo">
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="snep-body-top-buttons">
            <a class="btn btn-add" href="<?php echo $this->url ?>/add/ " role="button"><?php echo $this->translate("Add Session")?></a>
            <div class="snep-body-search">
              <?php if($this->key){ ?>
                <a class='sn-dash-add' href="<?php echo $this->baseUrl ?>/default/index/index?dashboard_add=<?php echo $this->key ?>" title="<?php echo $this->translate('Add to dashboard');?>"></a>
              <?php } ?>
            </div>
          </div>
        </div><br>
        <table class="table table-striped" id="listtable">
          <thead>
            <tr>
              <th class="text-center"><?php echo $this->translate('Name') ?> </th>
              <th class="text-center"><?php echo $this->translate('Path') ?> </th>
              <th class="text-center"><?php echo $this->translate('Type') ?> </th>
              <th class="text-center"><?php echo $this->translate('Files') ?> </th>
              <th class="text-center"><?php echo $this->translate('Actions') ?> </th>
            </tr>
          </thead>
          <tbody>
            <?php if($this->sections):
              foreach($this->sections as $class ):
                if ($class['name'] === 'default') {
                  $disabled= "disabled";
                } else {
                  $disabled = "";
                }?>
                <tr>
                  <td class="text-center"><?php echo $class['name'] ?></td>
                  <td class="text-center"><?php echo $class['directory'] ?></td>
                  <td class="text-center"><?php echo $this->modes[$class['mode']] ?></td>
                  <td class="text-center"><?php echo $class['count'] ?> </td>
                  <td class="text-center">
                    <a class="btn btn-default btn-sm"  href="<?php echo $this->url.'/file/section/'.$class['name'] ?>" role="button"> <?php echo $this->translate('Audios')?></a>
                    <a class="btn btn-edit btn-sm <?php echo $disabled ?>"  href="<?php echo $this->url.'/edit/section/'.$class['name'] ?>" role="button"><?php echo $this->translate('Edit')?></a>
                    <a class="btn btn-danger btn-sm <?php echo $disabled ?>"  href="<?php echo $this->url.'/remove/section/'.$class['name'] ?>" role="button" ><?php echo $this->translate('Delete')?></a>
                  </td>
                </tr>
              <?php endforeach ?>
            <?php endif ?>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

jQuery.noConflict();

jQuery(document).ready(function() {
  jQuery('#listtable').dataTable( {
    "pageLength": <?php echo $this->lineNumber ?>,
    "oLanguage": {
      "sUrl": "/snep/includes/javascript/datatables/media/language/pt-BR.json"
    },
    "bLengthChange": false,
  });
});
</script>




