<?php
/**
 *  This file is part of SNEP.
 *
 *  SNEP is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as
 *  published by the Free Software Foundation, either version 3 of
 *  the License, or (at your option) any later version.
 *
 *  SNEP is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with SNEP.  If not, see <http://www.gnu.org/licenses/lgpl.txt>.
 */
?>

<div class="row">
    <form id="defaultForm" method="post" class="form-horizontal" action="<?php echo $this->url(array("controller" => "music-on-hold", "action" => "remove"), null, true); ?>" METHOD="post">

        <div class="col-lg-12">
            <div class="panel panel-red">
                <div class="panel-heading">
                    <?php echo $this->translate("Delete Sound Files");?>
                </div>
                <div class="panel-body" align="center">
                    <p><?php echo $this->message ?></p>
                    <p><b><?php echo $this->confirmation ?></b></p>
                </div>

                <input type="hidden" name="id" value="<?php echo $this->id; ?>">

            </div>
        </div>

        <br>
        <div class="snep-body-footer-buttons">
                <button type="submit" class="btn btn-add" name="delete" value="delete"><?php echo $this->translate("Delete");?></button>
                &nbsp;&nbsp;&nbsp;
                <a class="btn btn-outline btn-add" href="javascript:window.history.go(-1)" role="button"><?php echo $this->translate("Cancel")?></a>

        </div>

    </form>
</div>