<div class="row">
	<form id="defaultForm" method="post" class="form-horizontal" action="<?php echo $this->url(array("controller" => "music-on-hold", "action" => "removefile"), null, true); ?>" METHOD="post">
 
        <?php
            echo $this->action( 'sneperror', 'error', null, array('error_message' => $this->remove_message, 'error_type' => 'alert', 'error_title' => $this->remove_title, 'error_buttons' => False) );
        ?>

        <input type="hidden" name="secao" value="<?php echo $this->file['secao']; ?>">
        <input type="hidden" name="arquivo" value="<?php echo $this->file['arquivo']; ?>">

        <br>
        <div class="snep-body-footer-buttons">
                <button type="submit" class="btn btn-add" name="delete" value="Delete"><?php echo $this->translate("Delete");?></button>
                &nbsp;&nbsp;&nbsp;
            	<a class="btn btn-outline btn-add" href="javascript:window.history.go(-1)" role="button"><?php echo $this->translate("Cancel")?></a>

        </div>   

	</form>
</div>


