<?php
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/agi_rules.css");
$this->headScript()->appendFile($this->baseUrl() . "/includes/javascript/scriptaculous/src/scriptaculous.js", 'text/javascript');
$this->headScript()->appendFile($this->baseUrl() . "/includes/javascript/snep.js", 'text/javascript');
$this->headScript()->appendFile($this->baseUrl() . "/includes/javascript/agi_rules.js", 'text/javascript');
?>

<hr>

<div class="form-group" data-intro="<?php echo $this->translate('For each Route you can add one or more actions to be executed in a sequence.');?>">
    <label class="col-sm-2 control-label"><?php echo $this->translate("Action");?></label>

    <div class="col-sm-8">

        <select class="form-control route-sm-5" name="action-name" id="action-name">
            <?php foreach ($this->element->getView()->actions as $class => $label): ?>
                <option value="<?php echo $class; ?>" label="<?php echo $label; ?>"><?php echo $label; ?></option>
            <?php endforeach; ?>
        </select>

        <button type="button" id="addActionButton" class="btn btn-add" value="Procurar">
            <?php echo $this->translate("Add Action"); ?>
        </button>

        <button type="button" id="cleanActionsButton" class="btn btn-add" value="Procurar">
            <?php echo $this->translate("Remove All"); ?>
        </button>

        &nbsp;
        <span class="input-group-btn">
            <img src="<?php echo $this->baseUrl(); ?>/images/ajax-loader1.gif" id="loader_icon" alt="<?php echo $this->translate("Loading"); ?>..." />
        </span>
    </div>
</div>


<table id="actions">
    <thead>
        <tr>
            <th><?php echo $this->translate("Actions"); ?></th>
            <th id="action-config-title"></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td id="actions-list-container">
                <div id="actions-list-scrollable">
                    <ol id="actions_list"></ol>
                </div>
            </td>
            <td id="actions-config"></td>
        </tr>
    </tbody>
</table>
<input name="actions_order" type="hidden" id="actions-order" value="" />
