<div class="form-group" data-intro="<?php echo $this->translate('You can Add a set of special Dates in the Date Alias menu to use here.<br>
It is useful for holidays or special work dates where you want have a different call flow.');?>">
    <label class="col-sm-2 control-label"><?php echo $this->translate("Valid Dates");?></label>
	<div class="col-sm-10" >
		<input type="hidden" name="datesValue" id="datesValue" value="--" />
		<ul id="dates" style="list-style:none; padding: 0px; margin: 0px;"></ul>
	</div>
</div>
