<div class="form-group" data-intro="<?php echo $this->translate('Destiny usually are the Called destination that you trying to filter.
It could be a Trunk, a Callerid(Contact), an Extension or any other option in the list.');?>">
    <label class="col-sm-2 control-label"><?php echo $this->translate("Destiny");?></label>
	<div class="col-sm-10" >
		<input type="hidden" name="dstValue" id="dstValue" value="--" />
		<ul id="dst" style="list-style:none; padding: 0px; margin: 0px;"></ul>
	</div>
</div>
