<div class="form-group" data-intro="<?php echo $this->translate('Source usually are the Caller of source that you trying to filter.<br>
It could be a Trunk, a Callerid(Contact), an Extension or any other option in the list.');?>">
	<label class="col-sm-2 control-label"><?php echo $this->translate("Source");?></label>
	<div class="col-sm-10" >
		<input type="hidden" name="srcValue" id="srcValue" value="--" />
		<ul id="orig" style="list-style:none; padding: 0px; margin: 0px;"></ul>
	</div>
</div>
