<?php
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/index.css");
$this->headScript()->appendFile($this->baseUrl() . '/includes/javascript/scriptaculous/lib/prototype.js');
$this->headScript()->appendFile($this->baseUrl() . '/includes/javascript/removeItem.js');
$this->headScript()->appendFile($this->baseUrl() . '/includes/javascript/selectBox.js');
echo $this->render('filter.phtml');
?>
<table>
    <thead>
        <tr>
            <th class="numeric"> <?php echo $this->translate('Code') ?> </th>
            <th> <?php echo $this->translate('Name') ?> </th>
            <th> <?php echo $this->translate('Created') ?> </th>
            <th> <?php echo $this->translate('Updated') ?> </th>
            <th colspan="2" class="action"> <?php echo $this->translate('Actions') ?> </th>
        </tr>
    </thead>
    <tbody>
        <?php
        $c = 0;
        if ($this->profiles):
            foreach ($this->profiles as $profile):
                ?>

        <?php ($c ? $c = 0 : $c = 1 ); ?>
                <tr class="c<?php echo $c ?>">
                    <td class="numeric"> <b> <?php echo $profile['id'] ?> </b> </td>
                    <td> <?php echo $profile['name'] ?> </td>
                    <td> <?php echo date('d/m/Y H:i:s', strtotime($profile['created'])) ?> </td>
                    <td> <?php echo date('d/m/Y H:i:s', strtotime($profile['updated'])) ?> </td>
                    <td class="action">
                        <a class="alterar" href="<?php echo $this->url ?>/edit/id/<?php echo $profile['id'] ?>">
        <?php echo $this->translate('Edit') ?>
                        </a>
                    </td>

                    <td class="action">
                        <?php if ($profile['id'] != 1) { ?>
                                <?php $this->remove_msg = $this->translate("Do you really wish to remove this item?"); ?>
                            <span class="excluir" onclick="remove_item('<?php echo $this->url ?>', '<?php echo $profile['id'] ?>', '<?php echo $this->remove_msg ?>')">
                            <?php echo $this->translate('Delete') ?>
                            </span>
        <?php } ?>
                    </td>

                </tr>
            <?php endforeach ?>
<?php endif ?>
</table>

<?php echo $this->render('pagination.phtml') ?>