<form  action="<?php echo $this->url(array("controller" => "sound-files", "action" => "synchronize"), null, true); ?>" METHOD="post">
    <?php
    $this->headLink()->appendStylesheet($this->baseUrl() . "/css/add.css");
    $this->headLink()->appendStylesheet($this->baseUrl() . "/css/index.css");
    $this->headScript()->appendFile($this->baseUrl() . '/includes/javascript/scriptaculous/lib/prototype.js');
    ?>

    <?php if ($this->message): ?>
        <span class="<?php echo $this->msgclass; ?>"><?php echo $this->message; ?></span>

    <?php endif; ?>


    <?php if ($this->submit) { ?>

        <?php if ($this->dadosdb) { ?>
            <?php if ($this->messagedb): ?>
                <span class="<?php echo $this->msgclass; ?>"><?php echo $this->messagedb; ?></span>
            <?php endif; ?>
            <div class="list_soundsfalse">
                <?php echo $this->dadosdb; ?>
            </div>
        <?php } ?>

        <br><br>

        <?php if ($this->dadosdir) { ?>
            <?php if ($this->messagedir): ?>
                <span class="<?php echo $this->msgclass; ?>"><?php echo $this->messagedir; ?></span>
            <?php endif; ?>
            <div class="list_soundstrue">
                <?php echo $this->dadosdir; ?>
            </div>
        <?php } ?>



        <dl id="login_form">
            <div class="form_element">

                <dd><input type="submit" value="<?php echo $this->translate("Synchronize"); ?>" /></dd>
            </div>
        </dl>

    <?php } ?>


