<?php
$this->headScript()->appendFile($this->baseUrl() . "/includes/javascript/scriptaculous/src/scriptaculous.js", 'text/javascript');
$this->headScript()->appendFile($this->baseUrl() . "/includes/javascript/snep.js", 'text/javascript');
echo $this->form;
?>

<script language="javascript" type="text/javascript">

    var phone = new Array();

    window.onload = function() {
        phoneObj = new MultiWx('phone', StringField);

<?php echo $this->dataphone; ?>

        phoneObj.render();
    }

    function atualizaValues() {
        $('phoneValue').value = phoneObj.getValue();
    }

    Event.observe($('contactsForm'), 'submit', atualizaValues);

</script>


