<script type="text/javascript" src="/snep/includes/javascript/formValidation.js"></script>
<script type="text/javascript" src="/snep/includes/javascript/form/bootstrap.js"></script>

<div class="row">          
    <form id="defaultForm" method="post" class="form-horizontal" action="<?php echo $this->url(array("controller" => "contacts", "action" => "export"), null, false); ?>" METHOD="post">

        <div class="col-lg-4">
	        <div class="panel panel-green">
	            <div class="panel-heading">
	                <?php echo $this->translate("Export Contacts");?>
	            </div>
	            <div class="panel-body" align="center">
	                
	            	<div class="form-group">
			        	<label class="col-sm-4 control-label"><?php echo $this->translate("Select a contact group to export");?></label>
			        	<div class="col-sm-4">
			        		<select class="form-control" name="group" id="group">
			        			<?php foreach($this->groups as $key => $group){ ?>
						    		<option value='<?php echo $key;?>'><?php echo $group;?></option>
						    	<?php } ?>

							</select>
						</div>
					</div>

	            </div>
	        </div>
	    </div>   
        
        <br>
        <div class="snep-body-footer-buttons">
            <button type="submit" class="btn btn-add" name="save" value="save"><?php echo $this->translate("Save");?></button>
            &nbsp;&nbsp;&nbsp;
        	<a class="btn btn-outline btn-add" href="javascript:window.history.go(-1)" role="button"><?php echo $this->translate("Cancel")?></a>
        </div>
    </form>
</div>