<?php if(!isset($this->csvData)){?>
  <div class="row">
    <form id="defaultForm" method="post" class="form-horizontal" action="<?php echo $this->url(array("controller" => "contacts", "action" => "import"), null, true); ?>" METHOD="post" enctype="multipart/form-data">
      <div class="col-lg-12">
	  	<div class="alert alert-info"><?php echo $this->message ?></div>
        <div class="panel panel-orange">
          <div class="panel-heading"><?php echo $this->translate("Import Contacts");?></div>
		  <div class="panel-body" align="center">
			<div class="form-group">
			  <label class="col-sm-5 control-label" style="padding-top: 0;"><?php echo $this->translate("Filename");?>:</label>
			  <div class="col-sm-6 text-left ">
				<input type="file" id="file" name="file" accept=".csv" >
			  </div>
	        </div>
		  </div>
	    </div>
	  </div><br>
	  <div class="snep-body-footer-buttons">
	    <button type="submit" class="btn btn-add" name="import" value="import"><?php echo $this->translate("Import");?></button>&nbsp;&nbsp;&nbsp;
	    <a class="btn btn-outline btn-add" href="javascript:window.history.go(-1)" role="button"><?php echo $this->translate("Cancel")?></a>
	  </div>
    </form>
  </div>
<?php }else{ ?>
	
  <div class="row">
    <form id="defaultForm" method="post" class="form-horizontal" action="<?php echo $this->url(array("controller" => "contacts", "action" => "csvprocess"), null, true); ?>" METHOD="post">
      <div class="col-lg-4">
	    <div class="panel panel-orange">
	      <div class="panel-heading"><?php echo $this->translate("Select a contact group");?></div>
		  <div class="panel-body" align="center">
		   	<div class="form-group">
		      <label class="col-sm-2 control-label"><?php echo $this->translate("Group");?>:</label>
			  <div class="col-sm-10">
				<select class="form-control" name="group" id="group" >
			      <?php foreach($this->groups as $key => $group){ ?>
					<option value='<?php echo $key ?>'><?php echo $group;?></option>
				  <?php } ?>
				</select>
			  </div>
			</div>
		  </div>
		</div>
	  </div> 

	  <div class="col-lg-8">
	    <div class="panel-body panel-orange" style="padding-top:0;">
	      <div class="panel-heading"><?php echo $this->translate("Set the relationship column x data");?></div>
	      <div class="table-responsive">
	        <table class="table table-striped table-bordered table-hover">
	          <thead>
	            <tr>
	              <?php for($cont=0;$cont<$this->contCol;$cont++){
	              $colun = "colun[".$cont."]"; ?>
	                <th>
		              <select class="form-control" name='<?php echo $colun?>' id='<?php echo $colun?>' >
						<?php echo $this->fields;?>
					  </select>
		            </th>
	              <?php } ?>
	            </tr>
	          </thead>
	        <tbody>

		    <?php foreach ($this->csvData as $key => $value) { ?>
	          <tr>
	           	<?php for($cont=0;$cont<$this->contCol;$cont++){?>
	              <td><?php echo $value[$cont] ?></td>
		        <?php } ?>
		      </tr>
		    <?php } ?>
	      </tbody>
	    </table>
	  </div>
	</div> 
  </div><br>
  <div class="snep-body-footer-buttons">
    <button type="submit" class="btn btn-add" name="import" value="import"><?php echo $this->translate("Save");?></button>&nbsp;&nbsp;&nbsp;
	<a class="btn btn-outline btn-add" href="javascript:window.history.go(-2)" role="button"><?php echo $this->translate("Cancel")?></a>
  </div>
</form>
</div>

<?php } ?>
