<div class= "row">
  <div class="tab-content">
    <div class="tab-pane active" id="demo">
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="snep-body-top-buttons">
            <a class="btn btn-add" href="<?php echo $this->url ?>/add/ " role="button"><?php echo $this->translate("Add Contact")?></a>
 
            <?php if($this->contacts): ?>
              <a class="btn btn-outline btn-add" href="<?php echo $this->url ?>/multiRemove/ " role="button"><?php echo $this->translate("Remove multiple")?></a>
            <?php endif;?>
              <a class="btn btn-outline btn-add" href="<?php echo $this->url ?>/import/ " role="button"><?php echo $this->translate("Import CSV")?></a>
              <div class="snep-body-search">
                <?php if($this->key){ ?>
                  <a class='sn-dash-add' href="<?php echo $this->baseUrl ?>/default/index/index?dashboard_add=<?php echo $this->key ?>" title="<?php echo $this->translate('Add to dashboard');?>"></a>
                <?php } ?>
              </div>
            </div>
          </div><br> 

          <table class="table table-striped" id="listtable">
            <thead>
              <tr>
                <th class="text-center"><?php echo $this->translate('Code');?></th>
                <th class="text-center"><?php echo $this->translate('Name');?></th>
                <th class="text-center"><?php echo $this->translate('Group');?></th>
                <th class="text-center"><?php echo $this->translate('City');?></th>
                <th class="text-center"><?php echo $this->translate('Phone');?></th>
                <th class="text-center"><?php echo $this->translate('Actions');?></th>
              </tr>
            </thead>
          <tbody>
            <?php if($this->contacts):
              foreach($this->contacts as $contact ): ?>
                <tr>
                  <td class="text-center"> <b> <?php echo $contact['ide'] ?> </b> </td>
                  <td class="text-center"> <?php echo $contact['nome'] ?> </td>
                  <td class="text-center"> <?php echo $contact['name'] ?> </td>
                  <td class="text-center"> <?php echo $contact['city'] ?> - <?php echo $contact['state'] ?> </td>
                  <td class="text-center"><?php echo ($contact['phone'] != "")? $this->formatter->fmt_telefone(array("a" =>$contact['phone'])) : " "; ?></td>
                  <td class="text-center">
                    <a class="btn btn-edit btn-sm"  href="<?php echo $this->url ?>/edit/id/<?php echo $contact['ide'] ?>" role="button"><?php echo $this->translate('Edit')?></a>
                    <?php $this->remove_msg = $this->translate("Do you really wish to remove this item?");?>
                    <a class="btn btn-danger btn-sm" href="<?php echo $this->url ?>/remove/id/<?php echo $contact['ide'] ?>" role="button"><?php echo $this->translate('Delete')?></a>
                  </td>
                </tr>
              <?php endforeach ?>
            <?php endif ?>
          </tbody>
        </table>
      </div>
    </div> 
  </div> 
</div> 

<script type="text/javascript">

jQuery.noConflict();

jQuery(document).ready(function() {
  jQuery('#listtable').dataTable( {
    "pageLength": <?php echo $this->lineNumber ?>,
    "oLanguage": {
      "sUrl": "/snep/includes/javascript/datatables/media/language/pt-BR.json"
    },
    "bLengthChange": false,
  });
});
</script>
