<?php
/**
 *  This file is part of SNEP.
 *
 *  SNEP is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  SNEP is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with SNEP.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<div class="row">
    <div class="tab-content">
        <div class="tab-pane active">
            <fieldset>
                <legend><?php echo $this->translate("About");?></legend>
            </fieldset>
            <?php echo $this->translate("
            SNEP is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
            <br /><br />
            SNEP is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
            <br /><br />
            You should have received a copy of the GNU General Public License along with SNEP.  If not, see http://www.gnu.org/licenses.
            ") ;?>
        </div>
        <br>
        <div class="tab-pane active">
            <fieldset>
                <legend><?php echo $this->translate("Use terms and Privacy");?></legend>
            </fieldset>
            <?php echo $this->translate("
            Using this free software you agree to share use statistics to improve your use experience.<br>
            We collect information to provide better services to all of our users – from figuring out basic stuff like which language you speak, to more complex things <br>
            like which hardwares manufacturer, Extensions and queues quantities you have.
            ") ;?>
        </div>
        <br />
        <div>
            <fieldset>
                <legend><?php echo $this->translate("Team");?></legend>
            </fieldset>
            <ul>
                <li>
                    <?php echo $this->translate("Flavio H. Somensi [ flavio@opens.com.br ]- Developer") ;?>
                </li>
                <li>
                    <?php echo $this->translate("Tiago Zimmermann [ tiago.zimmermann@opens.com.br ] - Developer
                        ") ;?>
                </li>
                <li>
                    <?php echo $this->translate("Daian Conrad [ daian.conrad@opens.com.br ] - Asterisk specialist") ;?>
                </li>
                <li>
                    <?php echo $this->translate("Douglas Conrad [ douglas.conrad@opens.com.br ] - Opens CEO") ;?>
                </li>
                <li>
                    <?php echo $this->translate("Dina Jumann [ dina.jumann@opens.com.br ] - Web designer ") ;?>
                </li>
            </ul>
        </div>
        <div>
            <fieldset>
                <legend><?php echo $this->translate("Copyright");?></legend>
            </fieldset>
            <?php echo $this->translate("Opens Tecnologia ") ;?><br />
            <?php echo $this->translate("Rua dos Cisnes, 541 ") ;?></br >
            <?php echo $this->translate("Cidade Universitária Pedra Branca") ;?></br >
            <?php echo $this->translate("88137-300 - Palhoça - SC - Brasil") ;?></br >
            <?php echo $this->translate("http://www.opens.com.br") ;?>
            </br >
            <?php echo $this->translate("copyright(c) All rights reserved") ;?>
    </div>
    <br />
</div> <!-- /.row -->
