<?php
$this->headLink()->appendStylesheet( $this->baseUrl() . "/css/index.css" );
$this->headScript()->appendFile('/snep/includes/javascript/scriptaculous/src/scriptaculous.js');
$this->headScript()->appendFile('/snep/includes/javascript/registrations.js');
?>

<div>
<form name="tabela" id="tabela" action="<?php echo $this->url(array("controller" => "calls-report", "action" => "graphic"), null, true); ?>" METHOD="post">
		<div class="graphic">
        <input type="submit" value="<?php echo $this->translate("Graphic"); ?>" />
    	</div>
  <input type="hidden" value="" id="selected" />
     <table align="center">
	   <thead>
               <tr>
                  <td class="cen"><?php echo $this->seq; ?></td>
                  <td class="cen"><?php echo $this->calldate; ?></td>
                  <td class="esq"><?php echo $this->origin; ?></td>
                  <td class="esq"><?php echo $this->destination; ?></td>
                  <td class="esq"><?php echo $this->operator; ?></td>
                  <td class="esq"><?php echo $this->callstatus; ?></td>
                  <td class="esq"><?php echo $this->duration; ?></td>
                  <td class="esq"><?php echo $this->conversation; ?></td>
                  <td class="esq"><?php echo $this->cost_center; ?></td>
                  <td class="esq"><?php echo $this->city;?> - <?php echo $this->state;?></td>
               </tr>
            </thead>
            <?php $c = 0; ?>
			<?php foreach( $this->call_list as $id => $callsList ): ?>
                        <?php ( $c ? $c = 0 : $c = 1 ); ?>
				<tr  class="c<?php echo $c ?>" >
					<td>
					  <?php echo $callsList['id']; ?>
					</td>
					<td>
						<?php echo $callsList['dia']; ?> 
					</td>
					<td>
						<?php echo $callsList['src']; ?> 
					</td>
					<td>
						<?php echo $callsList['dst']; ?> 
					</td>
					<td>
                            <?php
                                if (preg_match("/Local/i", $callsList['dstchannel'])) {
                                    echo strTok(str_replace('Local/', '', $callsList['dstchannel']), "@");
                                }
                                if(isset($callsList['operador'])) {
                                    echo $callsList['dstchannel'];
                                } else {
                                    echo "";    
                                }
                            ?> 
                        </td>
					<td>
						<?php echo $callsList['disposition']; ?> 
					</td>
					<td>
						<?php echo $callsList['duration'] ?>	
					</td>
					<td>
						<?php echo $callsList['billsec'] ?>	
					</td>
					<td>
						<?php echo $callsList['nome'] ?>
					</td>
					<td>
						<?php echo $callsList['city'] ?>

					</td>
			<?php endforeach ?>
            </tr>

			<tr>
               <td colspan="12">
                  <b><?php echo $this->sub_total; ?>:</b>
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			   	   <?php echo $this->answered;?>:&nbsp;
					<b><?php echo $this->totals['answered'];?></b>
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					<?php echo $this->nanswered;?>:&nbsp;
					<b><?php echo $this->totals['notanswer'];?></b>
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					<?php echo $this->busy;?>:&nbsp;
					<b><?php echo $this->totals['busy'];?></b>
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					<?php echo $this->failure;?>:&nbsp;
					<b><?php echo $this->totals['fail'];?></b>
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					<?php echo $this->other;?>:&nbsp;
					<b><?php echo $this->totals['oth'];?></b>
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
               </td>
            </tr>
         </table>
      </form>

<?php echo $this->render('pagination.phtml');  ?>

</div>
