<html>
  <head>
    <!--Load the AJAX API-->
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">

      // Load the Visualization API and the piechart package.
      google.load('visualization', '1.0', {'packages':['corechart']});

      // Set a callback to run when the Google Visualization API is loaded.
      google.setOnLoadCallback(totalStatus);
      google.setOnLoadCallback(totalType);
      google.setOnLoadCallback(typeColumn);
      google.setOnLoadCallback(typeLine);

      <?php 
          
          foreach ($this->period as $value) {  
              $values .= '[\''.$value[0].'\','.$value[1].','.$value[2].','.$value[3].','.$value[4].'],'; 
          }

          $values = substr($values,0, -1); 
      ?>
      
      function totalStatus() {

        var status = new google.visualization.DataTable();
        status.addColumn('string', 'Topping');
        status.addColumn('number', 'Slices');
        status.addRows([
          ['<?php echo $this->translate('Answered');?>', <?php echo $this->totals['ANSWERED'] ?>],
          ['<?php echo $this->translate('No Answer');?>', <?php echo $this->totals['NO ANSWER'] ?>],
          ['<?php echo $this->translate('Busy');?>', <?php echo $this->totals['BUSY'] ?>],
          ['<?php echo $this->translate('Failed');?>', <?php echo $this->totals['FAILED'] ?>]
        ]);

        var options = {'title':'<?php echo $this->translate("Status")?>',
                       'width':400,
                       'height':270,
                       'is3D' : true,
                       'chartArea':{left:25,top:20,width:'90%',height:'75%'}};

        var chart = new google.visualization.PieChart(document.getElementById('piechart_3d'));
        chart.draw(status, options);
      }

      function totalType() {

        var status = new google.visualization.DataTable();
        status.addColumn('string', 'Topping');
        status.addColumn('number', 'Slices');
        status.addRows([
          ['<?php echo $this->translate('Incoming');?>', <?php echo $this->type['E'] ?>],
          ['<?php echo $this->translate('Outgoing ');?>', <?php echo $this->type['S'] ?>],
          ['<?php echo $this->translate('Other');?>', <?php echo $this->type['O'] ?>],
        ]);

        var options = {'title':'<?php echo $this->translate("Cost Center")?>',
                       'width':400,
                       'height':270,
                       'is3D' : true,
                       'chartArea':{left:25,top:20,width:'90%',height:'75%'}};

        var chart = new google.visualization.PieChart(document.getElementById('piechart_3dType'));
        chart.draw(status, options);
      }

     
      function typeColumn() {

        var data = google.visualization.arrayToDataTable([
        ['<?php echo $this->translate('Date');?>',
        '<?php echo $this->translate('Answered');?>', 
        '<?php echo $this->translate('No Answer');?>',
        '<?php echo $this->translate('Busy');?>',
        '<?php echo $this->translate('Failed');?>' ], 
        <?php echo $values; ?>
      ]);
        
      var options = {
        width: 900,
        height: 500,
        legend: { position: 'top', maxLines: 4 },
        isStacked: true,
        chartArea: {left:50,top:10,width:'98%',height:'80%'}
      };
          
          var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));

          chart.draw(data, options);

      }

      function typeLine() {
        var data = google.visualization.arrayToDataTable([
        ['<?php echo $this->translate('Date');?>',
        '<?php echo $this->translate('Answered');?>', 
        '<?php echo $this->translate('No Answer');?>',
        '<?php echo $this->translate('Busy');?>',
        '<?php echo $this->translate('Failed');?>' ], 
        <?php echo $values; ?>
      ]);

        var options = {
          vAxis: {minValue: 0},
          chartArea: {left:40,top:10,width:'83%',height:'75%'}
        };

        var chart = new google.visualization.AreaChart(document.getElementById('chart_div2'));
        chart.draw(data, options);
      }

    </script>
  </head>

  <body>
    <h2><?php echo $this->translate("Totals")?></h2>
    <table> 
        <tr> 
          <td style="width: 350px"><div id="piechart_3d"></div></td>
          <td style="width: 350px"><div id="piechart_3dType"></div></td> 
        </tr> 
    </table> 
    <br>
    <h2><?php echo $this->translate("States By Period")?></h2>
    <br>
    <div id="chart_div"></div>
    <div id="chart_div2"></div>
        
  </body>
</html>