<?php 
$this->headScript()->appendFile($this->baseUrl() . '/includes/javascript/graphic/flot/jquery.flot.js');
$this->headScript()->appendFile($this->baseUrl() . '/includes/javascript/graphic/flot/jquery.flot.min.js');
$this->headScript()->appendFile($this->baseUrl() . '/includes/javascript/graphic/flot/jquery.flot.pie.js');
$this->headScript()->appendFile($this->baseUrl() . '/includes/javascript/graphic/flot/jquery.flot.categories.js');
$this->headScript()->appendFile($this->baseUrl() . '/includes/javascript/graphic/flot/jquery.flot.resize.js');
$this->headScript()->appendFile($this->baseUrl() . '/includes/javascript/graphic/flot/jquery.flot.time.js');
?>

<div class="row">

    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <?php echo $this->translate('Data by Period')?>
            </div>

            <div class="panel-body">
                
                <div id="content">
                    <div id="placeholder" class="demo-placeholder"></div>
                        <p id="choices"></p>
                    
                </div> 

            </div> 
        </div>
    </div>
    
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <?php echo $this->translate('Totals')?>
            </div>

            <div class="panel-body">
                <div class="flot-chart">
                    <div id="totals" class="demo-placeholder"></div>
                    <div id="menu-graphic">
                        <button class="btn btn-outline btn-add" id="totals-1"><?php echo $this->translate('Default Options')?></button>
                        <button class="btn btn-outline btn-add" id="totals-2"><?php echo $this->translate('Rectangular Pie')?></button>
                        <button class="btn btn-outline btn-add" id="totals-3"><?php echo $this->translate('Donut Hole')?></button>
                       
                    </div>
                </div>
            </div> 
        </div>
    </div> 

    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <?php echo $this->translate('Type')?>
            </div>

            <div class="panel-body">
                <div class="flot-chart">
                    <div id="type" class="demo-placeholder"></div>
                    <div id="menu-graphic">
                        <button class="btn btn-outline btn-add" id="type-1"><?php echo $this->translate('Default Options')?></button>
                        <button class="btn btn-outline btn-add" id="type-2"><?php echo $this->translate('Rectangular Pie')?></button>
                        <button class="btn btn-outline btn-add" id="type-3"><?php echo $this->translate('Donut Hole')?></button>
                       
                    </div>
                </div>
            </div> 
        </div>
    </div>
    

</div>

<script type="text/javascript">

//TOTALS
jQuery.noConflict();
jQuery(function() {

    var data = [
        { 
            label: '<?php echo $this->translate('Answered'); ?>',    
            data: <?php echo $this->totals->ANSWERED ?>,
            color: '#228B22'  
        },
        {
            label: '<?php echo $this->translate('No Answer'); ?>',
            data: <?php echo $this->totals->NOANSWER ?>,
            color: '#EE3B3B'
        },
        {
            label: '<?php echo $this->translate('Busy'); ?>',
            data: <?php echo $this->totals->BUSY ?>,
            color: '#EEC900'
        },
        {
            label: '<?php echo $this->translate('Failed'); ?>',
            data: <?php echo $this->totals->FAILED ?>,
            color: '#660099'
        }
    ];

    var totals = jQuery("#totals");

    jQuery("#totals-1").click(function() {

        totals.unbind();

        jQuery.plot(totals, data, {
            series: {
                pie: { 
                    show: true,
                    radius: 1,
                    label: {
                        show: true,
                        radius: 3/4,
                        formatter: labelFormatter,
                        background: { 
                            opacity: 0.5,
                            color: "#000"
                        }
                    }
                }
            },
            legend: {
                show: true
            }
        });
    });

    jQuery("#totals-2").click(function() {

        totals.unbind();

        jQuery.plot(totals, data, {
            series: {
                pie: { 
                    show: true,
                    radius: 500,
                    label: {
                        show: true,
                        radius: 3/4,
                        formatter: labelFormatter,
                        background: { 
                            opacity: 0.5,
                            color: "#000"
                        }
                    }
                }
            },
            legend: {
                show: true
            }
        });
    });

    jQuery("#totals-3").click(function() {

        totals.unbind();
        
        jQuery.plot(totals, data, {
            series: {
                pie: { 
                    innerRadius: 0.5,
                    show: true,
                    label: {
                        show: true,
                        formatter: labelFormatter,
                        threshold: 0.1
                    }
                }
            },
            legend: {
                show: true
            }
        });
    });

    // Show the initial default chart
    jQuery("#totals-1").click();
  
});

function labelFormatter(label, series) {
    
    return "<div style='font-size:8pt; text-align:center; padding:2px; color:white;'>" + label + "<br/>" + series.data[0][1] + "(" + Math.round(series.percent) + "%)</div>";
}

</script>

<script type="text/javascript">

//TYPE
jQuery.noConflict();
jQuery(function() {

    var data = [
        { 
            label: '<?php echo $this->translate('Incoming'); ?>',    
            data: <?php echo $this->type->E; ?>,
            color: '#228B22'  
        },
        {
            label: '<?php echo $this->translate('Outgoing'); ?>',
            data: <?php echo $this->type->S; ?>,
            color: '#EE3B3B'
        },
        {
            label: '<?php echo $this->translate('Other'); ?>',
            data: <?php echo $this->type->O; ?>,
            color: '#660099'
        }
    ];

    var type = jQuery("#type");

    jQuery("#type-1").click(function() {

        type.unbind();

        jQuery.plot(type, data, {
            series: {
                pie: { 
                    show: true,
                    radius: 1,
                    label: {
                        show: true,
                        radius: 3/4,
                        formatter: labelFormatter,
                        background: { 
                            opacity: 0.5,
                            color: "#000"
                        }
                    }
                }
            },
            legend: {
                show: true
            }
        });
    });

    jQuery("#type-2").click(function() {

        type.unbind();

        jQuery.plot(type, data, {
            series: {
                pie: { 
                    show: true,
                    radius: 500,
                    label: {
                        show: true,
                        radius: 3/4,
                        formatter: labelFormatter,
                        background: { 
                            opacity: 0.5,
                            color: "#000"
                        }
                    }
                }
            },
            legend: {
                show: true
            }
        });
    });

    jQuery("#type-3").click(function() {

        type.unbind();
        
        jQuery.plot(type, data, {
            series: {
                pie: { 
                    innerRadius: 0.5,
                    show: true,
                    label: {
                        show: true,
                        formatter: labelFormatter,
                        threshold: 0.1
                    }
                }
            },
            legend: {
                show: true
            }
        });
    });

    // Show the initial default chart
    jQuery("#type-1").click();
  
});

</script>

<script type="text/javascript">

jQuery.noConflict();
jQuery(function() {

    <?php   
    $answered = '';
    $noanswer = '';
    $busy = '';
    $failed = '';
    foreach($this->calldate as $key => $value){
        
        $timestamp = strtotime(str_replace("/", "-", $key));
        (isset($value->ANSWERED)) ? $answered .= '['.$timestamp.'000'.','.$value->ANSWERED.'],' : $answered .= '['.$timestamp.'000'.',0],' ;
        (isset($value->NOANSWER)) ? $noanswer .= '['.$timestamp.'000'.','.$value->NOANSWER.'],' : $noanswer .= '['.$timestamp.'000'.',0],' ;
        (isset($value->BUSY)) ? $busy .= '['.$timestamp.'000'.','.$value->BUSY.'],' : $busy .= '['.$timestamp.'000'.',0],' ;
        (isset($value->FAILED)) ? $failed .= '['.$timestamp.'000'.','.$value->FAILED.'],' : $failed .= '['.$timestamp.'000'.',0],' ;
           
    }
        $answered = substr($answered,0, -1); 
        $noanswer = substr($noanswer,0, -1); 
        $busy = substr($busy,0, -1); 
        $failed = substr($failed,0, -1); 
    ?>

    var datasets = {
        "answer": {
            label: '<?php echo $this->translate('Answer'); ?>',
            data: [<?php echo $answered; ?>]
        },        
        "noanswer": {
            label: '<?php echo $this->translate('No Answer'); ?>',
            data: [<?php echo $noanswer; ?>]
        },
        "busy": {
            label: '<?php echo $this->translate('Busy'); ?>',
            data: [<?php echo $busy; ?>]
        },
        "failed": {
            label: '<?php echo $this->translate('Failed'); ?>',
            data: [<?php echo $failed; ?>]
        }
    };
   
    // hard-code color indices to prevent them from shifting as
    // countries are turned on/off
    var i = 0;
    jQuery.each(datasets, function(key, val) {
        val.color = i;
        ++i;
    });

    // insert checkboxes 
    var choiceContainer = jQuery("#choices");
    jQuery.each(datasets, function(key, val) {
        choiceContainer.append("&nbsp;&nbsp;&nbsp;&nbsp;<input type='checkbox' name='" + key +
            "' checked='checked' id='id" + key + "'></input>" +
            "<label for='id" + key + "'>"
            + val.label + "</label>");
    });

    choiceContainer.find("input").click(plotAccordingToChoices);

    function plotAccordingToChoices() {

        var data = [];

        choiceContainer.find("input:checked").each(function () {
            var key = jQuery(this).attr("name");
            if (key && datasets[key]) {
                data.push(datasets[key]);
            }
        });

        if (data.length > 0) {
            jQuery.plot("#placeholder", data, {
                yaxis: {
                    min: 0
                },
                lines: { show: true },
                points: { show: true },
                xaxis: { mode: "time", timeformat: "%d/%m/%y"}
            });
        }
    }

    plotAccordingToChoices();

});

</script>