<?php
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/index.css");
$this->headScript()->appendFile($this->baseUrl() . '/includes/javascript/scriptaculous/lib/prototype.js');
$this->headScript()->appendFile($this->baseUrl() . '/includes/javascript/removeItem.js');
$this->headScript()->appendFile($this->baseUrl() . '/includes/javascript/selectBox.js');
echo $this->render('filter.phtml');
?>

<table>
    <thead>
        <tr>
            <th class="numeric"> <?php echo Snep_Order::getLink($this, 'Code', 'id') ?></th>
            <th> <?php echo Snep_Order::getLink($this, 'Name', 'name') ?></th>
            <th> <?php echo Snep_Order::getLink($this, 'Created', 'created') ?></th>
            <th> <?php echo Snep_Order::getLink($this, 'Updated', 'updated') ?></th>
            <th colspan="4" class="action"> <?php echo $this->translate('Actions') ?> </th>
        </tr>
    </thead>
    <tbody>
        <?php
        $c = 0;
        if ($this->profiles):
            foreach ($this->profiles as $profile):
                ?>

                <?php ($c ? $c = 0 : $c = 1 ); ?>
                <tr class="c<?php echo $c ?>">
                    <td class="numeric"> <b> <?php echo $profile['id'] ?> </b> </td>
                    <td> <?php echo $profile['name'] ?> </td>
                    <td> <?php echo date('d/m/Y H:i:s', strtotime($profile['created'])) ?> </td>
                    <td> <?php echo date('d/m/Y H:i:s', strtotime($profile['updated'])) ?> </td>
                    <td class="action">
                         <?php if ($profile['id'] != 1) { ?>
                        <a class="alterar" href="<?php echo $this->url ?>/edit/id/<?php echo $profile['id'] ?>">
                            <?php echo $this->translate('Edit') ?>
                             <?php } ?>
                        </a>
                    </td>

                    <td class="action">
                        <a class="membros" onclick="javascript:alert('<?=$this->translate("Users who do not have individual permissions are listed. To change the group of users with these permissions is necessary to make editing user.")?>')" href="<?php echo $this->url ?>/member/id/<?php echo $profile['id'] ?>">
                            <?php echo $this->translate('Members') ?>
                        </a>
                    </td>

                    <td class="action">
                        <?php if ($profile['id'] != 1) { ?>
                            <a class="permissao" href="<?php echo $this->url ?>/permission/id/<?php echo $profile['id'] ?>">
                                <?php echo $this->translate('Permission') ?>
                            </a>
                        <?php } ?>
                    </td>

                    <td class="action">
                        <?php if ($profile['id'] != 1) { ?>
                            <?php $this->remove_msg = $this->translate("Do you really wish to remove this item?"); ?>
                            <span class="excluir" onclick="remove_item('<?php echo $this->url ?>', '<?php echo $profile['id'] ?>', '<?php echo $this->remove_msg ?>')">
                                <?php echo $this->translate('Delete') ?>
                            </span>
                        <?php } ?>
                    </td>

                </tr>
            <?php endforeach ?>
        <?php endif ?>
</table>

<?php echo $this->render('pagination.phtml') ?>