<?php
$this->headScript()->appendFile($this->baseUrl() . "/includes/javascript/scriptaculous/src/scriptaculous.js", 'text/javascript');
$this->headScript()->appendFile($this->baseUrl() . "/includes/javascript/snep.js", 'text/javascript');
$this->headScript()->appendFile($this->baseUrl() . "/includes/javascript/scriptaculous/src/scriptaculous.js", 'text/javascript');
$this->headScript()->appendFile($this->baseUrl() . '/includes/lightbox.js', 'text/javascript');
?>

<?php if ($this->message): ?>
    <span class="<?php echo $this->msgclass; ?>"><?php echo $this->message; ?></span>
<?php endif; ?>

<div id="lightboxbody">
    <a id="lightboxLink" href="javascript:void(0);"><img src="/snep/imagens/help.png" class="right"></a>
</div>

<div id="containerDiv">
    <h2><?php echo $this->translate("Alias de Expressão Regular"); ?></h2>

    <?php echo $this->translate("Alias de expressão regular é usado para facilitar a criação de regras de negócio que partilhem de expressões regulares comuns."); ?>
    <br><?php echo $this->translate("Para cadastrar um novo alias basta escolher um nome e determinar uma ou mais expressões regulares que serão usadas para comparar origens e destinos nas regras de negócio."); ?>
    <br><?php echo $this->translate("Para que o alias seja válido basta que pelo menos uma das expressões casem com o parâmetro especificado na regra."); ?>
    <br>
    <br>
    <a id="closeLink" href="javascript:void(0);"><?php echo $this->translate("Back"); ?></a><br><br>
</div>     

<?php echo $this->form; ?>

<script language="javascript" type="text/javascript">

    var expr = new Array();

    window.onload = function() {
        exprObj = new MultiWx('expr', StringField);
<?php echo $this->dataExprAlias; ?>
        exprObj.render();
    }

    function atualizaValues() {
        $('exprValue').value = exprObj.getValue();
    }

    Event.observe($('expressionAliasForm'), 'submit', atualizaValues);
</script>

<script language="javascript" type="text/javascript">
    var test;

    Event.observe(window, 'load', function() {
        test = new Lightbox('containerDiv');
    });
    Event.observe('lightboxLink', 'click', function() {
        test.open();
    });
    Event.observe('closeLink', 'click', function() {
        test.close();
    });
</script>