<div class= "row">
  <div class="tab-content">
    <div class="tab-pane active" id="demo">
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="snep-body-top-buttons">
            <a class="btn btn-add" href="<?php echo $this->url ?>/add/ " role="button"><?php echo $this->translate("Add Queue")?></a>
            <div class="snep-body-search">
              <?php if($this->key){ ?>
                <a class='sn-dash-add' href="<?php echo $this->baseUrl ?>/default/index/index?dashboard_add=<?php echo $this->key ?>" title="<?php echo $this->translate('Add to dashboard');?>"></a>
              <?php } ?>
            </div>
          </div>
        </div><br>
        <table class="table table-striped" id="listtable">
          <thead>
            <tr>
              <th class="text-center"><?php echo $this->translate('Name');?></th>
              <th class="text-center"><?php echo $this->translate('Audio Class');?></th>
              <th class="text-center"><?php echo $this->translate('Strategy');?></th>
              <th class="text-center"><?php echo $this->translate('SLA');?></th>
              <th class="text-center"><?php echo $this->translate('Timeout');?></th>
              <th class="text-center"><?php echo $this->translate('Static Members');?></th>
              <th class="text-center"><?php echo $this->translate('Actions');?></th>
            </tr>
          </thead>
          <tbody>
            <?php if ($this->queues) :
              foreach ($this->queues as $cha => $queue): ?>
                <tr>
                  <td class="text-center"><?php echo $queue['name'] ?></td>
                  <td class="text-center"><?php echo $queue['musiconhold'] ?></td>
                  <td class="text-center"><?php echo $queue['strategy'] ?></td>
                  <td class="text-center"><?php echo $queue['servicelevel'] ?></td>
                  <td class="text-center"><?php echo $queue['timeout'] ?></td>
                  <td class="text-center"><?php echo $queue['members'] ?></td>
                  <td class="text-center">
                    <a class="btn btn-info btn-sm"  href="<?php echo $this->url ?>/members/id/<?php echo $queue['name'] ?>" role="button"><?php echo $this->translate('Members')?></a>
                    <a class="btn btn-edit btn-sm"  href="<?php echo $this->url ?>/edit/id/<?php echo $queue['name'] ?>" role="button"><?php echo $this->translate('Edit')?></a>
                    <a class="btn btn-danger btn-sm"  href="<?php echo $this->url ?>/remove/id/<?php echo $queue['name'] ?>" role="button"><?php echo $this->translate('Delete')?></a>
                  </td>
                </tr>
              <?php endforeach ?>
            <?php endif ?>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
jQuery.noConflict();

jQuery(document).ready(function() {
  jQuery('#listtable').dataTable( {
    "pageLength": <?php echo $this->lineNumber ?>,
    "oLanguage": {
      "sUrl": "/snep/includes/javascript/datatables/media/language/pt-BR.json"
    },
    "bLengthChange": false,
  });
});
</script>
