<form id="defaultForm" method="post" class="form-horizontal" action="<?php echo $this->url(array("controller" => "dates-alias", "action" => $this->action), null, false); ?>" METHOD="post">
<div class="row">
    <div class="form-group">
        <label class="col-sm-1 control-label"><?php echo $this->translate("Name");?></label>
        <div class="col-sm-4">
            <input type="text" class="form-control" name="name" placeholder='<?php echo $this->translate("Name")?>' value='<?php echo $this->alias[0]['name'];?>'/>
        </div>
    </div>
    
    <?php if ($this->action == "add") { ?>
        
        <table id="tableExpr" class="order-list table">
            <tbody>
                <tr>
                    <td class="text-right col-sm-1">
                        <label class="control-label"><?php echo $this->translate("Date");?></label>
                    </td>
                    <td class="text-right control-label col-sm-3">
                        <input type="text" class="snep-datetimepicker form-control" name="date[]" required placeholder="YYYY-MM-DD ou MM-DD" />
                    </td>
                    <td class="text-right col-sm-2">
                        <label class="control-label"><?php echo $this->translate("Time Range");?></label>
                    </td>
                    <td class="text-right control-label col-sm-3">
                        <input type="text" class="snep-timepicker form-control" name="timerange[]" required value="00:00-23:59" />
                    </td>
                    <td>
                        <button type="button" class="boxadd add_field"></button>
                        <button type="button" class="boxremove del_field" style="display: none;">
                    </td>
                </tr>
            </tbody>
        </table>

        <!--<div class="form-group">
            <label class="col-sm-1 control-label"><?php echo $this->translate("Date");?></label>
            <div class="col-sm-3">
                <div class="input-group">
                    <input type="text" class="snep-datetimepicker form-control" name="date[]" required placeholder="YYYY-MM-DD ou MM-DD" />
                    <div class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </div>
                </div>
            </div>
            <label class="col-sm-2 control-label"><?php echo $this->translate("Time Range");?></label>
            <div class="col-sm-3">
                <div class="input-group">
                    <input type="text" class="snep-timepicker form-control" name="timerange[]" required value="00:00-23:59" />
                    <div class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </div>
                </div>
            </div>
            <div class="col-sm-2">
                <button id="add" type="button" class="boxadd add_field"></button>
                <button id="del" type="button" class="boxremove del_field"></button>
            </div>
        </div>-->
    <?php } else {?>

        <table id="tableExpr" class="order-list table">
            <tbody>
                <?php $number = count($this->alias);
                foreach ($this->alias as $key => $alias) {?>
                    <tr>
                        <td class="text-right col-sm-1">
                            <label class="control-label"><?php echo $this->translate("Date");?></label>
                        </td>
                        <td class="text-right control-label col-sm-4">
                            <input class="snep-datetimepicker form-control" type="text" name="date[]" required placeholder="<?php echo $this->translate('Date (YYYY-MM-DD)')?>" value="<?php echo $alias['date']; ?>"/>
                            <input type="hidden" name="listid[]" value="<?php echo $alias['list_id']; ?>"/>
                        </td>
                        <td class="text-right col-sm-2">
                            <?php echo $this->translate("Time Range");?>
                        </td>
                        <td class="text-right control-label col-sm-4">
                            <input class="snep-timepicker form-control" type="text" name="timerange[]" required placeholder="<?php echo $this->translate('Time Range (HH:MM-HH:MM)')?>" value="<?php echo $alias['timerange']; ?>"/>
                        </td>
                        <?php if ($key === 0 && $number === 1) { ?>
                            <td>
                                <button type="button" class="boxadd add_field"></button>
                                <button type="button" class="boxremove del_field" style="display: none;"></button>
                            </td>
                        <?php } elseif (($key+1) === $number) { ?>
                            <td>
                                <button type="button" class="boxadd add_field"></button>
                                <button type="button" class="boxremove del_field"></button>
                            </td>
                        <?php } else { ?>
                            <td><button type="button" class="boxadd add_field" style="display: none;"></button>
                                <button type="button" class="boxremove del_field"></button>
                            </td>
                        <?php } ?>
                    </tr>            
                <?php } ?>
            <tbody>
        </table>
    <?php } ?>
    <div class="form-group">
        <input type="hidden" name="id" value="<?php echo $this->id; ?>">
        <div class="snep-body-footer-buttons">
            <button type="submit" class="btn btn-add" name="save" value="save"><?php echo $this->translate("Save");?></button>&nbsp;&nbsp;&nbsp;
            <a class="btn btn-outline btn-add" href="javascript:window.history.go(-1)" role="button"><?php echo $this->translate("Cancel")?></a>
        </div>
    </div>
</form>

<script type="text/javascript">

jQuery.noConflict();

jQuery(document).ready(function(){
    jQuery('#defaultForm').validate({
        rules: {
            name: {
                required: true,
                minlength: 5,
                maxlength: 30,
                lettersAndNumbersOnly: true
            },
            "date[]": {
                required: true,
                regex: /^([0-9][0-9][0-9][0-9]-)?(0[1-9]||1[0-2])-(0[1-9]||[12][0-9]||3[01])$/
            },
            "timerange[]": {
                required: true,
                regex: /^([01][0-9]||2[0-3]):(0[0-9]||[1-5][0-9])-([01][1-9]||2[0-3]):(0[0-9]||[1-5][0-9])$/
            }
        },
        messages: {
            name: {
                required: "<?php echo $this->translate('The name field is required'); ?>",
                minlength: "<?php echo $this->translate('Please enter at least {0} characters.'); ?>",
                maxlength: "<?php echo $this->translate('Please enter no more than {0} characters.'); ?>",
                lettersAndNumbersOnly: "<?php echo $this->translate('Please enter letters and numbers only'); ?>"
            },
            "date[]": {
                required: "<?php echo $this->translate('The date is required'); ?>",
                regex: "<?php echo $this->translate('The date need to be in the formats: YYYY-MM-DD or MM-DD'); ?>"
            },
            "timerange[]": {
                required: "<?php echo $this->translate('The time range is required'); ?>",
                regex: "<?php echo $this->translate('The time range need to be in the formats: HH:MM-HH:MM'); ?>"
            }
        },
        highlight: function(element) {
            jQuery(element).closest('.control-group').removeClass('success').addClass('error');
        },
        success: function(element) {
            element
            .text('OK!').addClass('valid')
            .closest('.control-group').removeClass('error').addClass('success');
        }
    });

    // Add lines
        jQuery("table.order-list").on("click",".add_field", function(e){ //user click on remove text
            //e.preventDefault();

            jQuery(".add_field").hide(); // Hide ADD buton   
            jQuery(".del_field").show();

            // Mount new line
            var newRow = jQuery("<tr>");
            var cols = "";
            cols += '<td class="text-right col-sm-1">';
            cols += '  <label class="control-label">';
            cols += '    <?php echo $this->translate("Date");?>';
            cols += '  </label>' ;
            cols += '</td>' ;
            cols += '<td class="text-right control-label col-sm-3">' ;
            cols += '  <input type="text" class="snep-datetimepicker form-control" name="date[]" required placeholder="YYYY-MM-DD ou MM-DD" />';
            cols += '</td>'
            cols += '<td class="text-right col-sm-2">';
            cols += '  <label class="control-label">';
            cols += '    <?php echo $this->translate("Time Range");?>';
            cols += '  </label>' ;
            cols += '</td>' ;
            cols += '<td class="text-right control-label col-sm-3">' ;
            cols += '  <input type="text" class="snep-timepicker form-control" name="timerange[]" required value="00:00-23:59" />';
            cols += '</td>'
            cols += '<td><button type="button" class="boxadd add_field"></button>';
            cols += '<button type="button" class="boxremove del_field" /></button></td>'  ;

            newRow.append(cols);
            jQuery("table.order-list").append(newRow);

        });
        // Remove lines
        jQuery("table.order-list").on("click",".del_field", function(e){ //user click on remove text
            //e.preventDefault(); 
            jQuery(this).closest("tr").remove();
            jQuery('#tableExpr tr:last').find(".add_field").show();
            if (jQuery("#tableExpr tr").length == 1) {
                jQuery('#tableExpr tr:last').find(".del_field").hide();
            } 
        });
});
</script>
