<div class= "row">
  <div class="tab-content">
    <div class="tab-pane active" id="demo">
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="snep-body-top-buttons">
            <a class="btn btn-add" href="<?php echo $this->url ?>/add/ " role="button"><?php echo $this->translate("Add Date Alias")?></a>
            <div class="snep-body-search">
              <?php if($this->key){ ?>
                <a class='sn-dash-add' href="<?php echo $this->baseUrl ?>/default/index/index?dashboard_add=<?php echo $this->key ?>" title="<?php echo $this->translate('Add to dashboard');?>"></a>  &nbsp;|&nbsp;
              <?php } ?>
            </div>
          </div>
        </div><br>
        <table class="table table-striped" id="listtable">
          <thead>
            <tr>
              <th class="text-center"><?php echo $this->translate('Code');?></th>
              <th class="text-center"><?php echo $this->translate('Name');?></th>
              <th class="text-center"><?php echo $this->translate('Date Alias');?></th>
              <th class="text-center"><?php echo $this->translate('Actions');?></th>
            </tr>
          </thead>
          <tbody>
            <?php foreach ($this->aliases as $value) { ?>
              <tr>
                <td class="text-center" style="width:10%" data-type="numeric" data-sort-initial="true"><?php echo $value['id'] ?></td>
                <td class="text-center"><?php echo $value['name'] ?></td>
                <td class="text-center"><span class="label label-primary"><?php echo $value['cont'] ?></span></td>
                <td class="text-center">
                  <a class="btn btn-edit btn-sm"  href="<?php echo $this->url ?>/edit/id/<?php echo $value['id'] ?>" role="button"><?php echo $this->translate('Edit')?></a>
                  <a class="btn btn-danger btn-sm"  href="<?php echo $this->url ?>/remove/id/<?php echo $value['id'] ?>" role="button"><?php echo $this->translate('Delete')?></a>
                </td>
              </tr>
            <?php } ?>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

jQuery.noConflict();

jQuery(document).ready(function() {
  jQuery('#listtable').dataTable( {
    "pageLength": <?php echo $this->lineNumber ?>,
    "oLanguage": {
      "sUrl": "/snep/includes/javascript/datatables/media/language/pt-BR.json"
    },
    "bLengthChange": false,
  });
});
</script>
