<?php
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/action_configs.css");
$this->headScript()->appendFile($this->baseUrl() . "/includes/javascript/scriptaculous/src/scriptaculous.js", 'text/javascript');
$this->headScript()->appendFile($this->baseUrl() . '/includes/lightbox.js', 'text/javascript');
?>
<table>
    <tbody>
        <?php
        if ($this->success) {
            ?>
            <tr>
                <td class="success"><?php echo $this->translate('Atualizado com sucesso'); ?></td>
            </tr>
        <?php } ?>
    <div id="lightboxbody">
        <a id="lightboxLink" href="javascript:void(0);"><img src="/snep/imagens/help.png" class="right"></a>
    </div>

    <div id="containerDiv">
        <h2><?php echo $this->translate("Configurações Padrão - Configurar");?></h2>

        <?php echo $this->translate("O formulário de configuração de ação é gerado automaticamente a partir 
        dos parâmetros da ação. Caso a configuração de algum parâmetro não esteja 
        clara verifique o manual do usuário ou consulte o suporte técnico.");?>
        <br>
        <br>
        <a id="closeLink" href="javascript:void(0);"><?php echo $this->translate("Back"); ?></a><br><br>
    </div>
    <tr>
        <td><?php echo $this->form; ?></td>
    </tr>
</tbody>
</table>

<script language="javascript" type="text/javascript">
    var test;

    Event.observe(window, 'load', function() {
        test = new Lightbox('containerDiv');
    });
    Event.observe('lightboxLink', 'click', function() {
        test.open();
    });
    Event.observe('closeLink', 'click', function() {
        test.close();
    });
</script>
