<?php
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/action_configs.css");
$this->headScript()->appendFile($this->baseUrl() . "/includes/javascript/scriptaculous/src/scriptaculous.js", 'text/javascript');
?>

<table>
    <tbody>
        <?php
        if ($this->success) {
            ?>
            <tr>
                <td class="success"><?php echo $this->translate('Updated successfully'); ?></td>
            </tr>
        <?php } ?>

        <tr>
            <td><?php echo $this->form; ?></td>
        </tr>
    </tbody>
</table>

